/**
 * GENERATED by scripts/import-model.ts from fleet-near.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../imported";

export const MODEL = lazyModel("fleetNear", () => import("./fleetNear.data"), { deferred: true });
