/**
 * GENERATED by scripts/import-model.ts from overflow-sign.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import type { ImportedModel } from "../imported";

export const KEY = "overflowSign";

export const DATA: ImportedModel = {
  "materials": [
    {
      "role": "face",
      "surface": "metal",
      "tone": 1,
      "hex": "#1f5a46"
    },
    {
      "role": "frame",
      "surface": "metal",
      "tone": 1,
      "hex": "#e9e5d8"
    },
    {
      "role": "rail",
      "surface": "metal",
      "tone": 1,
      "hex": "#3b3d3f"
    },
    {
      "role": "stripe",
      "surface": "metal",
      "tone": 1,
      "hex": "#e8853c"
    },
    {
      "role": "post",
      "surface": "metal",
      "tone": 1,
      "hex": "#6f7270"
    },
    {
      "role": "footing",
      "surface": "concrete",
      "tone": 1,
      "hex": "#8f8b80"
    }
  ],
  "nodes": [
    {
      "name": "Faces",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -2.6500000953674316,
        2.200000047683716,
        -0.11999999731779099
      ],
      "scale": [
        0.00008087281896291848,
        0.0000411993598486872,
        0.0000036621651733513692
      ],
      "triangles": 4,
      "vertices": 8,
      "positions": "AAD+/wf+/wcAAAD+/wcA/f8HAAAA/f8H/f8HAP7/BwD+/wcAAAD9/wcA",
      "index": "AAICAwQCAgICAwQC",
      "ao": "Hx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "AAAAAA=="
    },
    {
      "name": "Frame",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -3.1000001430511475,
        0,
        -0.550000011920929
      ],
      "scale": [
        0.000094605940125159,
        0.00007660028963037329,
        0.000016784924450169495
      ],
      "triangles": 172,
      "vertices": 168,
      "positions": "wDakqAOy5gQA2tcEAAAA5cwBANnXBAD+kgcAAADa1wQAAADmzAEA2dcEAKEImgrGLrmCBwAAuoIHpsMEALmCBwAA8vYGgbUEySCp6wYAAKrrBt6mBACp6wYAAMcLgbUEp4kCuoIHAAAApsMEALmCBwAAyAuBtQTKIKrrBgAAAN6mBACp6wYAAAD34wSy7QEA5igAAACF8gEA5SgAqusG5igAAOUoAADmKIbyAQDlKACp6wYA5ALGMQAAhCHmKADFMQAAgyHlKM33AYQh5igAxjEAAIMh5SgAxjEAzvcBxjEAAIQh5igAxTEAAIMh5SjN9wGEIeYoAMYxAACDIeUoAMYxAM73AcYxAACEIeYoAMUxAACDIeUozfcBhCHmKADGMQAAgyHlKADGMQDO9wHGMQAAhCHmKADFMQAAgyHlKM33AYQh5igAxjEAAIMh5SgAxjEAzvcBxjEAAIQh5igAxTEAAIMh5SjN9wGEIeYoAMYxAACDIeUoAMYxAM73AcYxAACEIeYoAMUxAACDIeUozfcBhCHmKADGMQAAgyHlKADGMQDO9wHGMQAAhCHmKADFMQAAgyHlKM33AYQh5igAxjEAAIMh5SgAxjEAzvcBxjEAAIQh5igAxTEAAIMh5SjN9wGEIeYoAMYxAACDIeUoAMYxAM73AcYxAACEIeYoAMUxAACDIeUozfcBhCHmKADGMQAAgyHlKACHiQefwALq9AEAsq4HAAAAhfIBALGuBwD4KrKuBwAAsa4HAACyrgeG8gEAsa4HAMUxsq4HniUAmgoAAADBvAIAmQoAxjGaCgAAmQoAAJoKwrwCAJkKAJkzwbQHpgkAkAYAAACNzwIAjwYAvDuQBgAAjwYAAJAGjs8CAI8GANyKB5AGwy4Asq4HAAAAhfIBALGuBwD4KrKuBwAAsa4HAACyrgeG8gEAsa4HAPcqsq4HniUAmgoAAADBvAIAmQoAxjGaCgAAmQoAAJoKwrwCAJkKAOc5wbQHpgkAkAYAAACNzwIAjwYAvDuQBgAAjwYAAJAGjs8CAI8GANf8B5c9uNgCAJg9AAAA/f8HAJc9AIhCmD0AAJc9AACYPf7/BwCXPQDu+wYAAACYPQAAAP3/BwCXPQCIQpg9AACXPQAAmD3+/wcAlz0A",
      "index": "AAICAwQCAgICAwQCBwIGBwgNCgUBCAcKCw4CDxACAwEIBQYDAwkUCQoBEQESDxAEAwEIBQYCCQQICwwDAwIICQoBBQMIAwQEFxoCGxwZABoCGxwZABoCGxwhACIFGxwZGggCCQoHAAgCCQoHAAgCCQoHAAgFAQIHEAICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAAEEAQICAAEEAQICAAEJDAsBCAMBBgUKBAICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAAEEAQICAAEEAQICAAEJDAsBCAMBBgUKBAICAwQCAAEEAQICAAEEAQICAAEJDAsBCAMBBgUKBAICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAAEEAQICAAEEAQICAAEJDAsBCAMBBgUKBAICAwQCAAEEAQICAAEEAQICAAEJDAsBCAMBBgUKBAICAwQCAAEEAQICAAEEAQICAAEJDAsBCAMBBgUK",
      "ao": "ERkZERkRERkZERkRFhYWFhYWHx8fHx8fGBgeGB4dExodEx0eHx8fHx8fGhMeGh4dHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eGB4eGB4YEx0dEx0bHx8fHx8fGx0dGx0THh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eGBERGBEYHR0bHRsfGBERGBEZHxsdHx0dHRwdHR0dFhUVFhUUHx8dHx0eHx0eHx4fHx8dHx0dHx0dHx0fHx8dHx0dHx0dHx0fHx8dHx0dHx0dHx0fHx8dHx0dHx4dHx0fHx8dHx0dHx0dHx0fHx8eHx4dHx0dHx0fHx8dHx0dHx0dHx0fHx8dHx0dHx0dHx0fGBgYGBgZGRgbGRsYGRQVGRUYGBsYGBgYERERERERHx8fHx8fHx8fHx8fGhsbGhsaHx8fHx8fHBkZHBkcHx8fHx8fGB0dGB0YGBoaGBoYGB0dGB0YGBsaGBoYHBwcHBwcGBUUGBQYGBoYGBgYGRgZGRkYGBkbGBsYERERERERGhsbGhsaHx8fHx8fHx8fHx8fHx8fHx8fGRwcGRwZHx8fHx8fGB0dGB0ZGRsbGRsYFx0dFx0YGBoaGBoYHR0cHRwdGB0dGB0YGB0dGB0YGR0dGR0YGB0dGB0YHx8fHx8fGB0dGB0YGB0dGB0YGB0dGB0YGB0dGB0YHx8fHx8f",
      "aoLevels": 32,
      "material": "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQICAgICAgICAgICAgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFBQUFBQUFBQUFBQUFBQUFBQUFBQ=="
    }
  ],
  "markers": [
    {
      "name": "board.back",
      "position": [
        0,
        3.55,
        -0.12
      ]
    },
    {
      "name": "board.front",
      "position": [
        0,
        3.55,
        0.12
      ]
    }
  ]
};
