/**
 * GENERATED by scripts/import-model.ts from police-car.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../imported";

export const MODEL = lazyModel("policeCar", () => import("./policeCar.data"));
