/**
 * GENERATED by scripts/import-model.ts from vehicle-parts.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import type { ImportedModel } from "../imported";

export const KEY = "vehicleParts";

export const DATA: ImportedModel = {
  "materials": [
    {
      "role": "headlight",
      "surface": "glass",
      "tone": 1,
      "hex": "#fff2cf"
    },
    {
      "role": "headlight",
      "surface": "glass",
      "tone": 0.72,
      "hex": "#fff2cf"
    },
    {
      "role": "taillight",
      "surface": "glass",
      "tone": 1,
      "hex": "#ff4a3a"
    },
    {
      "role": "taillight",
      "surface": "glass",
      "tone": 0.72,
      "hex": "#ff4a3a"
    },
    {
      "role": "sign",
      "surface": "glass",
      "tone": 1,
      "hex": "#ffd66b"
    },
    {
      "role": "sign",
      "surface": "glass",
      "tone": 0.7,
      "hex": "#ffd66b"
    },
    {
      "role": "beacon",
      "surface": "glass",
      "tone": 1,
      "hex": "#ffb347"
    },
    {
      "role": "beacon",
      "surface": "glass",
      "tone": 0.7,
      "hex": "#ffb347"
    },
    {
      "role": "tyre",
      "surface": "fabric",
      "tone": 1,
      "hex": "#26282b"
    },
    {
      "role": "hub",
      "surface": "metal",
      "tone": 1,
      "hex": "#b9bcc0"
    },
    {
      "role": "spoke",
      "surface": "metal",
      "tone": 1,
      "hex": "#3d4045"
    }
  ],
  "nodes": [
    {
      "name": "LampsBus",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5400000214576721,
        0.4099999964237213,
        -2.2699999809265137
      ],
      "scale": [
        0.00001647974430327831,
        0.000021210039763371678,
        0.00006935225568465622
      ],
      "triangles": 50,
      "vertices": 40,
      "positions": "tC+uB+7+B9aqAQAAALRYANWqAQAAwPYFs1gA1qoBAAAAtFgA1aoBAAD9/wXhX6EL0L0BAAAAkmcAz70BAADC9gWRZwDQvQEAAACSZwDPvQEAAPmSBq4Hy/MHALRYANSqAQAAALNYANqXBQAAALRYANSqAQAAALNYAO+4Bq0HogvPvQEAANC9AZBnAM+9AQAA/v8Hj2cAz70BAADQvQGQZwDPvQEAAPehBbbTBdz0B5K/BQAAALpVAJG/BQAArwulXuEG8tUFAAAAkmcA8dUFAAA=",
      "index": "AAICAwQCAgICAwQCDRACERIPABACERIPABACERIPABAFCQoPCBACERIPABACERIPABACERIPABAFCQoPGAICAwQCAgICAwQCDQYKDxACCwEQDQ4DCwEUERIBEQESDxAEDQYKDxACCwEQDQ4DCwEUERIBEQESDxAEAgICAwQCBQgCCQoHAAgCCQoHAAgCCQoHAAgFAQIH",
      "ao": "Hx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "AAAAAAEBAQEBAQEBAQEBAQEBAQECAgICAwMDAwMDAwMDAwMDAwMDAwQEBQUFBQUFBQU="
    },
    {
      "name": "LampsHatchback",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.4399999976158142,
        0.33000001311302185,
        -1.190000057220459
      ],
      "scale": [
        0.000013427939196332165,
        0.000004119936075819578,
        0.00003631647386039396
      ],
      "triangles": 40,
      "vertices": 32,
      "positions": "9CL2Jf7/B7rRAQAAALSvAgC50QEAANzoBbOvAgC60QEAAAC0rwIAudEBAACt9AWp1QLBFd7oAQAAAKD7AgDd6AEAANzoBZ/7AgDe6AEAAACg+wIA3egBAACr9AW0rwK76gcAtK8CALrRAQAAALOvAgDmxQQAAAC0rwIAutEBAAAAs68CAM+LBvUlwhXb6AEAANzoAaD7AgDb6AEAAP7/B5/7AgDb6AEAANzoAaD7AgDb6AEAAA==",
      "index": "AAICAwQCAgICAwQCDRACERIPABACERIPABACERIPABAFCQoPCBACERIPABACERIPABACERIPABAFCQoPGAICAwQCAgICAwQCDQYKDxACCwEQDQ4DCwEUERIBEQESDxAEDQYKDxACCwEQDQ4DCwEUERIBEQESDxAE",
      "ao": "Hx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "AAAAAAEBAQEBAQEBAQEBAQEBAQECAgICAwMDAwMDAwMDAwMDAwMDAw=="
    },
    {
      "name": "LampsPickup",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5099999904632568,
        0.33000001311302185,
        -1.5199999809265137
      ],
      "scale": [
        0.000015564202043587605,
        0.000005188067499447298,
        0.00004638742598387163
      ],
      "triangles": 40,
      "vertices": 32,
      "positions": "mDKOHv7/B9CgAQAAALTpAgDPoAEAAP76BbPpAgDQoAEAAAC06QIAz6ABAACBhQbBhwPrENq0AQAAANKlAwDZtAEAAPz6BdGlAwDatAEAAADSpQMA2bQBAACLmQbq0gGR7wcAtOkCANCgAQAAALPpAgDWqgUAAAC06QIA0KABAAAAs+kCAJ/BBo8e7BDZtAEAANq0AdKlAwDZtAEAAP7/B9GlAwDZtAEAANq0AdKlAwDZtAEAAA==",
      "index": "AAICAwQCAgICAwQCDRACERIPABACERIPABACERIPABAFCQoPCBACERIPABACERIPABACERIPABAFCQoPGAICAwQCAgICAwQCDQYKDxACCwEQDQ4DCwEUERIBEQESDxAEDQYKDxACCwEQDQ4DCwEUERIBEQESDxAE",
      "ao": "Hx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "AAAAAAEBAQEBAQEBAQEBAQEBAQECAgICAwMDAwMDAwMDAwMDAwMDAw=="
    },
    {
      "name": "LampsSedan",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5,
        0.3199999928474426,
        -1.440000057220459
      ],
      "scale": [
        0.000015259021896696422,
        0.000002594033977100794,
        0.00004394598480874217
      ],
      "triangles": 40,
      "vertices": 32,
      "positions": "3B6ePP7/B6ThAQAAAPDhAwCj4QEAAKLhBe/hAwCk4QEAAADw4QMAo+EBAAC/6wWNngTjEeD1AQAAAKzaBADf9QEAAKLhBavaBADg9QEAAACs2gQA3/UBAADB6wW7eJnuBwDw4QMApOEBAAAA7+EDAPqoBAAAAPDhAwCk4QEAAADv4QMA//8FnTzkEd/1AQAA4PUBrNoEAN/1AQAA/v8Hq9oEAN/1AQAA4PUBrNoEAN/1AQAA",
      "index": "AAICAwQCAgICAwQCDRACERIPABACERIPABACERIPABAFCQoPCBACERIPABACERIPABACERIPABAFCQoPGAICAwQCAgICAwQCDQYKDxACCwEQDQ4DCwEUERIBEQESDxAEDQYKDxACCwEQDQ4DCwEUERIBEQESDxAE",
      "ao": "Hx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "AAAAAAEBAQEBAQEBAQEBAQEBAQECAgICAwMDAwMDAwMDAwMDAwMDAw=="
    },
    {
      "name": "LampsTaxi",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5,
        0.3199999928474426,
        -1.440000057220459
      ],
      "scale": [
        0.000015259021896696422,
        0.000014114595436345906,
        0.00004394598480874217
      ],
      "triangles": 50,
      "vertices": 40,
      "positions": "3B6IC/7/B6ThAQAAAMhYAKPhAQAAouEFx1gApOEBAAAAyFgAo+EBAAC/6wXPY+MR4PUBAAAA2m4A3/UBAACi4QXZbgDg9QEAAADabgDf9QEAAMHrBZEWme4HAMhYAKThAQAAAMdYAPqoBAAAAMhYAKThAQAAAMdYAP//BYkL5BHf9QEAAOD1AdpuAN/1AQAA/v8H2W4A3/UBAADg9QHabgDf9QEAAIXXA/KzBbj8At4e9I8B1AqS3AIAAN4e848B0woAAIBA3R70jwHVCpHcAgAA3R7zjwHWCg==",
      "index": "AAICAwQCAgICAwQCDRACERIPABACERIPABACERIPABAFCQoPCBACERIPABACERIPABACERIPABAFCQoPGAICAwQCAgICAwQCDQYKDxACCwEQDQ4DCwEUERIBEQESDxAEDQYKDxACCwEQDQ4DCwEUERIBEQESDxAEAgICAwQCAgICAwQCCwoBBwgFAgEGAwQBBgEJDAsB",
      "ao": "Hx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "AAAAAAEBAQEBAQEBAQEBAQEBAQECAgICAwMDAwMDAwMDAwMDAwMDAwQEBAQFBQUFBQU="
    },
    {
      "name": "LampsTractor",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.4699999988079071,
        0.8100000023841858,
        -1.0850000381469727
      ],
      "scale": [
        0.000014343480546514293,
        0.000017700465800351625,
        0.000037232014301067504
      ],
      "triangles": 50,
      "vertices": 40,
      "positions": "4uQB6gj+/wfcggEAAADQRgDbggEAAN6zA89GANyCAQAAANBGANuCAQAAz74DuU/9FMCYAQAAAKRYAL+YAQAA3rMDo1gAwJgBAAAApFgAv5gBAADbggUA/+oHAM5GANyCAQAAAM1GAOLkBQAAAM5GANyCAQAAAM1GAMncBukI/hTBmAEAAMKYAaJYAMGYAQAA/v8HoVgAwZgBAADCmAGiWADBmAEAAJFXotgGwuABAAD8KfhsAAAAAPsp24IBo1ixCMCYAQAAAADgOr+YAQAA",
      "index": "AAICAwQCAgICAwQCDRACERIPABACERIPABACERIPABAFCQoPCBACERIPABACERIPABACERIPABAFCQoPGAICAwQCAgICAwQCDQYKDxACCwEQDQ4DCwEUERIBEQESDxAEDQYKDxACCwEQDQ4DCwEUERIBEQESDxAEAgICAwQCAgcGAgEEAAMBBgUIAAcBCgkMAAsBDg0I",
      "ao": "Hx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "AAAAAAEBAQEBAQEBAQEBAQEBAQECAgICAwMDAwMDAwMDAwMDAwMDAwYGBwcHBwcHBwc="
    },
    {
      "name": "LampsVan",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5299999713897705,
        0.3199999928474426,
        -1.5700000524520874
      ],
      "scale": [
        0.00001617456233736997,
        0.0000067139695981660825,
        0.00004791333035636186
      ],
      "triangles": 40,
      "vertices": 32,
      "positions": "pjCiF/7/B8iaAQAAAPSiAwDHmgEAAOqEBvOiAwDImgEAAAD0ogMAx5oBAAC9jgaVugOnEPKtAQAAALrRAwDxrQEAAOiEBrnRAwDyrQEAAAC60QMA8a0BAADloQaudNXvBwD0ogMAyJoBAAAA86IDAMa3BQAAAPSiAwDImgEAAADzogMAt8gGoxeoEPGtAQAA8q0ButEDAPGtAQAA/v8HudEDAPGtAQAA8q0ButEDAPGtAQAA",
      "index": "AAICAwQCAgICAwQCDRACERIPABACERIPABACERIPABAFCQoPCBACERIPABACERIPABACERIPABAFCQoPGAICAwQCAgICAwQCDQYKDxACCwEQDQ4DCwEUERIBEQESDxAEDQYKDxACCwEQDQ4DCwEUERIBEQESDxAE",
      "ao": "Hx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "AAAAAAEBAQEBAQEBAQEBAQEBAQECAgICAwMDAwMDAwMDAwMDAwMDAw=="
    },
    {
      "name": "Wheel",
      "origin": [
        0,
        1,
        0
      ],
      "lo": [
        -0.5099999904632568,
        -1,
        -1
      ],
      "scale": [
        0.000015564202043587605,
        0.000030518043793392844,
        0.000030518043793392844
      ],
      "triangles": 64,
      "vertices": 34,
      "positions": "1KoB/v8HgIAEAPmVAYTqAtaqBQAAAPqVAYPqAtWqBf3/A/7/A9aqBQAA1aoFheoC+ZUB1qoFAADVqgX5lQGD6gLWqgUAANWqBfqVAYXqAtaqBQAA1aoFhuoC+ZUB1qoFAADVqgWE6gL6lQHWqgUAAJWtBus2huoCAPtZnNkBAJvZAfxZAJ3ZAftZAPtZm9kBAPxZndkBAJ7ZAftZAJzZAfxZ1q8HALqyAwD8WZvZAQCXswKYswIAndkB+1kA+1mb2QEA/Fmd2QEAntkB+1kAnNkB/Fnp1web2QGe2QH+/wcAAA==",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAhsGFhUYHSACISIfACACISIbABwCHR4ZABoCGxwXABgCGRoVABYCFxgTABQCFRYRABINAwQfBgEsKSoCLQYqLzADJQQoKywBJQQmKSoBIwQkJygBIQQiJSYBHwQgIyQBHRcsExQMHSAdAB4bAhoXABgVAhQRBAESEQQOCwIKCQIIBQIEHRwZBBYTAhIfFAIMBwIGAwsQ",
      "ao": "Hx8fHx8fHx8fHx8fHxwcHxwfGRQUGRQZFBkZFBkUHB8fHB8cHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8dHB8eHB4XFx4fFx8cHR8fHR8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx0fHx8fHBceHB4fFx0fFx8eHR8fHR8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "CAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICQkJCQkJCQkJCQoKCgoKCg=="
    }
  ],
  "markers": []
};
