/**
 * GENERATED by scripts/import-model.ts from site-kit-near.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../imported";

export const MODEL = lazyModel("siteKitNear", () => import("./siteKitNear.data"), { deferred: true });
