/**
 * GENERATED by scripts/import-model.ts from street2.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../imported";

export const MODEL = lazyModel("street2", () => import("./street2.data"));
