/**
 * GENERATED by scripts/import-model.ts from street2.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import type { ImportedModel } from "../imported";

export const KEY = "street2";

export const DATA: ImportedModel = {
  "materials": [
    {
      "role": "straw",
      "surface": "thatch",
      "tone": 1,
      "hex": "#d9bd68"
    },
    {
      "role": "twine",
      "surface": "thatch",
      "tone": 1,
      "hex": "#a48942"
    },
    {
      "role": "straw",
      "surface": "thatch",
      "tone": 0.76,
      "hex": "#d9bd68"
    },
    {
      "role": "body",
      "surface": "metal",
      "tone": 1,
      "hex": "#eaeaeb"
    },
    {
      "role": "lid",
      "surface": "metal",
      "tone": 1,
      "hex": "#f7f8f9"
    },
    {
      "role": "slit",
      "surface": "metal",
      "tone": 1,
      "hex": "#5a5f66"
    },
    {
      "role": "blade",
      "surface": "metal",
      "tone": 1,
      "hex": "#d3d6da"
    },
    {
      "role": "louvre",
      "surface": "metal",
      "tone": 1,
      "hex": "#b9bcc3"
    },
    {
      "role": "well",
      "surface": "glass",
      "tone": 1,
      "hex": "#8497a6"
    },
    {
      "role": "fan",
      "surface": "metal",
      "tone": 1,
      "hex": "#59616b"
    },
    {
      "role": "label",
      "surface": "metal",
      "tone": 1,
      "hex": "#fff0c2"
    },
    {
      "role": "post",
      "surface": "metal",
      "tone": 1,
      "hex": "#6b6f6d"
    },
    {
      "role": "canopy",
      "surface": "metal",
      "tone": 1,
      "hex": "#c9c3b4"
    },
    {
      "role": "sign",
      "surface": "metal",
      "tone": 1,
      "hex": "#68848b"
    },
    {
      "role": "frame",
      "surface": "metal",
      "tone": 1,
      "hex": "#4f5452"
    },
    {
      "role": "glass",
      "surface": "glass",
      "tone": 1,
      "hex": "#a8bcc4"
    },
    {
      "role": "wood",
      "surface": "timber",
      "tone": 1,
      "hex": "#9a7c58"
    },
    {
      "role": "board",
      "surface": "metal",
      "tone": 1,
      "hex": "#37423f"
    },
    {
      "role": "paper",
      "surface": "metal",
      "tone": 1,
      "hex": "#d6cfb8"
    },
    {
      "role": "line",
      "surface": "metal",
      "tone": 1,
      "hex": "#a9b4ab"
    },
    {
      "role": "leaf",
      "surface": "foliage",
      "tone": 1,
      "hex": "#ffffff"
    },
    {
      "role": "leg",
      "surface": "metal",
      "tone": 1,
      "hex": "#a6a9ad"
    },
    {
      "role": "tank",
      "surface": "metal",
      "tone": 1,
      "hex": "#dcdad4"
    },
    {
      "role": "tankTop",
      "surface": "metal",
      "tone": 1,
      "hex": "#b6b8bc"
    },
    {
      "role": "band",
      "surface": "metal",
      "tone": 1,
      "hex": "#a6a9ad"
    },
    {
      "role": "hatch",
      "surface": "metal",
      "tone": 1,
      "hex": "#a3a7ad"
    },
    {
      "role": "pipe",
      "surface": "metal",
      "tone": 1,
      "hex": "#98999e"
    }
  ],
  "nodes": [
    {
      "name": "Bale",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5081337690353394,
        0,
        -0.44999998807907104
      ],
      "scale": [
        0.00001550724861632225,
        0.00001550724861632225,
        0.000013733119343223348
      ],
      "triangles": 64,
      "vertices": 34,
      "positions": "gIAEgIAEuBzUqQHKmQO3HPbvAfXvAQC0ZrQqlH31qwL2qwIAAADWhQb2qwL1qwIA/f8Dh9QB3GDKmQPUqQG4HPXvAfbvAQDd/QK0ZumCBwAA1oUGwcUBqdYC6YIH9u8B9u8BAKnWAsHFAZR9AADWhQaq1gLCxQGUffXvAfXvAQCzZt39AumCBwAA1oUGqtYCw8UB6YIH9e8B+O8BAMLFAanWApR9AADWhQbBxQGq1gKUffbvAffvAQDe/QKxZumCBwAA1oUGwsUBqtYC6YIH9e8B9+8BAKrWAsTFAZR9AADWhQap1gLDxQGUffbvAfjvAQA=",
      "index": "AAICAgICAwQCAgICCQwCDQ4LCRgCBQgCCQoHBxICBQgCCQoHHSgCBQgCCQoHFyICBQgCCQoHLTgCBQgCCQoHJzICBTUGMC8yOQEGAwQBBgEIBQYBDRgFERILAgwKFRYNCAEEAQIHAggECwwBBxIFCwwHAggKERINCAEEAQIHAggECwwBBxIFCwwHAggKERINCAEEAQIHAggECwwBBzMCMjE2AjEELi0yQRoXDAQOHyoRCRQOLzoRGSQOPwQ0KTQx",
      "ao": "ExsTHh0eHh4eExMfHh4fHh8fExMbHR4eHR4eEx8THhMeHh4fExMTFBMTFBMcExMTExMTExMTExMTExQcExwTExMTEx0fEx8eExscExwdHh0eHh4THBwdHB0dHh4fHh8fHBMdHB0bHR4THRMeExMVExUcHx4THxMTExMTExMVHBMTHBMTExMTExMTExMTExMTExMVExUTExwTExMTExMdEx0VHh4THhMTExsbEx4fExMTExMTExMTExMTExMTExMT",
      "aoLevels": 32,
      "material": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAgICAgICAg=="
    },
    {
      "name": "Block",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.515500009059906,
        0,
        -0.515500009059906
      ],
      "scale": [
        0.000015732051851984618,
        0.000015716792117033197,
        0.000015732051851984618
      ],
      "triangles": 88,
      "vertices": 128,
      "positions": "6s0HAJQy1ZsHAAAA/tYGANabBwAA1ZsH/dYG1psHAP7WBgDWmwf91gYAAP7WBgCN2waWiwGN2wbGmgYAAMWaBgDGmgbGmgYAAPneBfvWBoJHrqMFAAAA+oQEAK2jBQAA/KUG+YQEzYIBAACtowUA+oQEAAAArqMFzYIB+YQE+6UGraMFAAAA+oQEAK6jBQAA+6UG+YQEzoIBAACuowUA+oQEAAAAraMFzoIB24MD/KUGAMNP2iuuowUAAADET9krraMFonwAAMNP2iuuowUAAADET9krraMFpHwAAMNP2iuuowUAAADET9krraMFonwAAMNP2iuuowUAAADET9krzoIB5/QCzYIB2ivDTwAAAK2jBdkrxE8AAKJ8rqMF2ivDTwAAAK2jBdkrxE8AAKR8rqMF2ivDTwAAAK2jBdkrxE8AAKJ8rqMF2ivDTwAAAK2jBdkrxE8AzYIB5/QCzYIBAMNP2SutowUAAADET9orrqMFonwAAMNP2SutowUAAADET9orrqMFpHwAAMNP2SutowUAAADET9orrqMFonwAAMNP2SutowUAAADET9orzYIB5/QCzoIB2SvDTwAAAK6jBdorxE8AAKJ8raMF2SvDTwAAAK6jBdorxE8AAKR8raMF2SvDTwAAAK6jBdorxE8AAKJ8raMF2SvDTwAAAK6jBdorxE8AyOcF9uAC2cMDn6EBAJ+hAcsH6h2sEsCWAQDAlgH58gLpHeuoAcwH6h2sEuuoAekd9I4BrBLqHcwHqxLpHbrcAawS6h3LB/SOAekd7KgBzAfqHasSutwB6R2sEssH6h2rEuyoAekd844BqxLqHcsHv5YB7xXAlgHAlgEAv5YBAADt1AG/lgEAv5YB7dQBAAC/lgEAwJYBAADu1AHAlgEAwJYB6ZIB+gfllAIAAN4nwvoDAAAAAN0nn/0BAKH9AQAAxPoDAADeJwAAw/oD/JQBu4MC2L0FhosBAAAAzEUAhYsBAAA=",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIBwEGAwQEBwEMCQoCDQYKDxADBQQICwwBBQcMAwQEAwEEAQICAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAhsGFhUYAgICAAICAAICAAINAAQEAAQLEAICAwQCAgICAwQCAgICAwQC",
      "ao": "GBgfGB8fGBgfGB8fGBgfGB8fGBcfGB8fERERERESHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fGhoeGh4eGhoeGh4fGhofGh8fGhsfGh8fHB4eHB4cHB4fHB8cHR4fHR8cHh8eHh4eHB4dHB0cHB4eHB4cHB4eHB4cHh4eHh4eHB4eHB4cHB4eHB4dHB4eHB4cHh8eHh4eHB0eHB4cHB4eHB4cHB4eHB4cHh8fHh8eHBsdHB0dHBwdHB0dGxwdGx0dHBwdHB0dHBwdHB0cHBwdHB0dHBwdHB0cHBwdHB0dFhYXFxYWFhYXFxcWFhcWFhcWGhkaGhoZERERERERHx8fHx8f",
      "aoLevels": 32,
      "material": "AwMDAwMDAwMDAwQEBAQEBAQEBAQFBQUFBQUFBQYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBwcHBwcHBwcHBwcHBwcHBwgICAgICAkJCQkKCg=="
    },
    {
      "name": "BusStop",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -1.350000023841858,
        0,
        -0.699999988079071
      ],
      "scale": [
        0.00004211490210837791,
        0.00004425116495563335,
        0.000019073777370870527
      ],
      "triangles": 204,
      "vertices": 180,
      "positions": "3HYA6M0E/QwA0zEA+IcHAP4MANQx+Sb3hwfTMQD4hwcA/Qz3hwfUMQD4hwcA/gz3hwfUMQD4hwcA/Bn3hwcAAPiHBwCavQb3hwfTMf0MANMxAP7/BwD+DADUMfkm/f8H0zEA/v8HAP0M/f8H1DEA/v8HAP4M/f8H1DEA/v8HAPwZ/f8HAAD+/wcA6Y4F/f8HvdUBAPqlAQAAAMOWAgD5pQEAohb6pQEAAPmlAQAA+qUBxJYCAPmlAQD6pgMAAAD6pQEAAADDlgIA+aUBAKAW+qUBAAD5pQEAAPqlAcSWAgD5pQEAy94FyN0GwOsDAAD2UQCiWAAAnxyz5wcA4R8AAAC+lQfc6QeCPPZRAKFYAAAA9VEAoBwAAAC9lQcA4h8AjYsGrSrS6AfCrAQAAAD6NADBrAQAAOaoBekmrBcAhngAAADLmQMAhXgAkAuGeAAAhXgAAIZ4zJkDAIV4ALftBuXbBOOhB8SfBwAAsxS0EwDb9gYAAJCLB7MTqznDnwcAALQUtBMA3PYGAAC0FO7EBKw5sxS1EwC0FLYTqzmzFLUTAI+LB7YTrDm0FLUTALMUthOrObQUtRMA1qoCt7EElwihFgAAALixBACiFgAAoRa3sQTeSQC4sQQAoha3sQQAALixBADStwK3sQTdSZ8WAAAAuLEEAKAWAACfFrexBN5JALixBACgFrexBAAAuLEEAKfiBP3hA6UMAJAOAAAAkzEAjw4A3PYGkA4AAI8OAACQDpQxAI8OAIP2BrOEA9EyzRcAAADGoQIAzhcAAM0XxaECkDQAxqECAM4XxaECAADGoQIA/IwHxaECjzTNFwAAAMahAgDOFwAAzRfFoQKQNADGoQIAzhfFoQIAAMahAgCZrQHg8gK20AQAtqIBAAAAqzkAtaIBAITmAbaiAQAAtaIBAAC2ogGsOQC1ogEAvcYH4YEC6+gEkJgCAAAA7tMDAI+YAgAAkJgC7dMDowOPmAIAAADu0wMAkJgCAADqDu3TA6QD6KgCAAAA7tMDAOeoAgAA6KgC7dMDowPnqAIAAADu0wMA6KgCAADsDu3TA6QDjpgCAAAA7tMDAI2YAgAAjpgC7dMDowONmAIAAADu0wMAjpgCAACHvwW3wAXUggMAmBUAAADVxwIAlxUAtIcEmBUAAJcVAACYFdbHAgCXFQCeMLz8A/LpAazIAQAAAJaGAQCryAEAALYH+RacAcC5AQAAANwYAL+5AQAA7A6vNgDqmwEAAACuBgDpmwEAAADjGQDIhQEAAACuBgDHhQEAAADjGQCmbwAAAK4GAKVvAAA=",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAgQCBQYDAhMGDg0QAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAgQCBQYDAhMGDg0QAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAAICAgkEAAQCAgICAgICCQQCAAQJAwEQDQ4BDwEMCQoBAQEMCQoBCwEIBQYKEwEQDQ4BDQoIERIBCAICAwQCAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAgICAwQCAwEFCAcBBgEKBwgBCQ4CDxANEAsGBgUIDQwDBwgNAg4EERIHAggCCQoHCgcCBgUICQgDAwQHAggECwwHAhcGEhEUDxICExQREBEJHBsYAhMGDg0SAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQC",
      "ao": "GBgUGBQUGBgTGBMTGBkSGBISGBgSGBISGBgUGBQTGBgUGBQUGBgeGB4eGBgdGB0dGBgdGB0dGBgdGB0dGBgcGBwcGBgeGB4dGBgYGBgYGBgYGBgYGRgYGRgYGBgYGBgYERERERERERERERERGBgYGBgYGBgYGBgYGRgYGRgYGBgYGBgYERERERERERERERERHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fGh4eGh4YHx8eHx4fHx8fHx8fHBgYHBgcHx8fHx8fGR4TGRMRERUVERURERQeER4aHx8fHx8fEREbERsaGxwfGx8fHx8fHx8fHx8fHx8fGRkZGRkZGxsaGxoaHxgZHxkfGB8fGB8dHRgYHRgdGxYXGxcbGBgZGBkZGBgdGB0dERERERERGRkYGRgYGB8fGB8ZHxgdHx0fGB0dGB0YFhscFhwXHx8eHx4eHBwWHBYXHx4ZHxkZGxsYGxgWHx8eHx4eHBsWHBYXHx8ZHxkZGxwXGxcVERERERERGBgYGBgYERERERERGBkYGBgYGBcXGBcXFRUVFRUVGBgfGB8YGBkfGB8fGBgYGBgfGBgYGBgYGBgYGBgfGBgZGBkYGBgfGB8YGBkfGB8fHxwcHxwfHxweHx4fHx8fHx8fHx4bHxsfHh4fHh8fGxQUGxQbFRERFREVERQUERQRERERERERERERERERERQVERURFRERFREUHh4fHh8fHx4fHx8fHx8eHx4fHx8fHx8eHR0dHR0dHh4fHh8fHx8eHx4cHh4dHh0cHx8eHx4fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "CwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLDAwMDAwMDAwMDAwMDAwMDAwMDAwNDQ0NDQ0NDQ0NDQ0NDQ4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4PDw8PDw8PDw8PDw8QEBAQEBAQEBAQEBARERISExMTExMT"
    },
    {
      "name": "Hedge",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5,
        0,
        -0.3499999940395355
      ],
      "scale": [
        0.000015259021896696422,
        0.00001602197226392438,
        0.00001068131514578578
      ],
      "triangles": 22,
      "vertices": 15,
      "positions": "AAAAAPD6BJozgIAEsmYAAKHhBZkz//8DqLgHxsIDgIAE1keQhQH//wPVxwKOhQOAgAT1UQD//wOx5gSaM4CABAAA/v8DrI8F48wHAKuPBZkzAI6FB7LmAwCnuAGy5gMA5cwFmjM=",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgQCBQYDBwEQDQ4CEQYOExQDCQQMDxABCQQKDQ4BGRADAAMFCgkBHAUBAAQCBQYC",
      "ao": "GR8TGRMTHx8dHx0THx8THxMdHxkTHxMTExMfEx8ZEx4fEx8fHRMfHR8fExMZExkfGRkfHx8fHx8ZGRkfHx8fHx8Z",
      "aoLevels": 32,
      "material": "FBQUFBQUFBQUFBQUFBQUFBQUFBQUFA=="
    },
    {
      "name": "Row0",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5,
        0,
        -0.5
      ],
      "scale": [
        0.000015259021896696422,
        0.000015259020987187842,
        0.000015259021896696422
      ],
      "triangles": 22,
      "vertices": 15,
      "positions": "AAAAAIyEBPZRgIAEpmIAALHmBPVR//8DktwGgIAEgIAE7KMBAP//A/H7A4iuA4CABKZiAP//A7HmBPZRgIAEAAD+/wP6qASHrgcA+agE9VEAzJkHgIAEANHwAoiuAwD5qAT2UQ==",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgQCBQYDBwEQDQ4CEQYOExQDCQQMDxABCQQKDQ4BGRADAAMFCgkBHAUBAAQCBQYC",
      "ao": "GBoTGBMTHh4THhMTHh4THhMTGhgTGhMTExMaExoYExMeEx4eExMdEx0fExMYExgaGRkaGhwbGhsZGRkaGhwbGhsZ",
      "aoLevels": 32,
      "material": "FBQUFBQUFBQUFBQUFBQUFBQUFBQUFA=="
    },
    {
      "name": "Row1",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5,
        0,
        -0.4999999701976776
      ],
      "scale": [
        0.000015259021896696422,
        0.000015259021896696422,
        0.000015259020987187842
      ],
      "triangles": 18,
      "vertices": 15,
      "positions": "AAAAANbHBoCABICAAqi4AQAA/f8H//8D//8BAP7/B4CAAgAAgIACnooG/f8DAJ2KBv//AwAA/v8H/v8BxsIH/f8DAMXCB///AwAA/v8HgIAC0PAG/f8DAM/wBv//AwAA/v8H",
      "index": "AAICAwQCAwYCBwgFAgEIBQYCCQYGCwwDAgEGAwQCBwQGCQoDAgEGAwQCBwQGCQoDDwUBGgEE",
      "ao": "Hh8fHh8dHx4dHx0fHR8UHRQUHx0UHxQUFBQfFB8dFBQdFB0fHR8fHR8eHx0eHx4fGRsZGBsZ",
      "aoLevels": 32,
      "material": "FBQUFBQUFBQUFBQUFBQUFBQU"
    },
    {
      "name": "Row2",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5,
        0,
        -0.5
      ],
      "scale": [
        0.000015259021896696422,
        0.000015259021896696422,
        0.000015259021896696422
      ],
      "triangles": 22,
      "vertices": 15,
      "positions": "AAAAAJizBubMAYCABObMAQAA/f8H5cwB//8DkLAFgIAEgIAEgqwBAP//A/komLMCgIAE5swBAP//A/3/B+bMAYCABAAA/v8DjoUHl7MGAI2FB+XMAQD29AWAgAQAmJABmLMCAI2FB+bMAQ==",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgQCBQYDBwEQDQ4CEQYOExQDCQQMDxABCQQKDQ4BGRADAwUBDAMHHAUBBAICBwQE",
      "ao": "Gh0TGhMTHx4THxMTHh8THhMTHRoTHRMTExMdEx0aExMeEx4fExMfEx8eExMaExodGRkbGxwZGxsZGRkbGxwZGxsZ",
      "aoLevels": 32,
      "material": "FBQUFBQUFBQUFBQUFBQUFBQUFBQUFA=="
    },
    {
      "name": "Row3",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5,
        0,
        -0.5
      ],
      "scale": [
        0.000015259021896696422,
        0.000015259021896696422,
        0.000015259021896696422
      ],
      "triangles": 22,
      "vertices": 15,
      "positions": "AAAAAPqGBubMAYCABNZpAADP8AblzAH//wOOhQeAgASAgATwegD//wOD+QGYswKAgATWaQD//wPP8AbmzAGAgAQAAP7/A9zjBZezBgDb4wXlzAEAktwGgIAEALV4mLMCANvjBebMAQ==",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgQCBQYDBwEQDQ4CEQYOExQDCQQMDxABCQQKDQ4BGRADAAMFCgkBHAUBAAQCBQYC",
      "ao": "HR4THRMTHx8THxMTHx8THxMTHh4THhMTExMeEx4dExMfEx8fExMfEx8fExMdEx0eGRkbGxsbGxsZGRkaGhsbGhsZ",
      "aoLevels": 32,
      "material": "FBQUFBQUFBQUFBQUFBQUFBQUFBQUFA=="
    },
    {
      "name": "Tank",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.45460501313209534,
        0,
        -0.4779999852180481
      ],
      "scale": [
        0.000013873655699461215,
        0.000015564202043587605,
        0.000014587624482125524
      ],
      "triangles": 173,
      "vertices": 156,
      "positions": "2P8BAKyxAcdfAAD+A6DBAuYDzFcAAMlbn8ECjFf+A6DBAuMDylufwQLkA/0DoMEC4wP+A5/BAqbrA8dfAAD+A6DBAuQDzFcAAMlbn8ECjlf+A6DBAuUDylufwQLmA/0DoMEC5QOU5ASfwQK/mQXHXwAA/gOgwQLmA8xXAADJW5/BAoxX/gOgwQLjA8pbn8EC5AP9A6DBAuMD/gOfwQKm6wPHXwAA/gOgwQLkA8xXAADJW5/BAo5X/gOgwQLlA8pbn8EC5gP9A6DBAuUDuf4EhY8CwQmW4ATu3AEAgxsAAJXgBO3cAQCa+wQAAJXgBO7cAQCDGwAAluAE7dwBAKYvAP0sAO7cAbPCBAAA2hkA7dwBtMIEAACN3AQA7twBtMIEAADaGQDt3AGzwgSlLwD9LJXgBO7cAQCEGwAAluAE7dwBAJn7BAAAluAE7twBAIQbAACV4ATt3AEApS8A/iwA7twBtMIEAADZGQDt3AGzwgQAAI7cBADu3AGzwgQAANkZAO3cAbTCBMq+Bvz6Ac2sA5m8AQCt9gEAosYEAJq8AQCu9gHZ7AOhxgS51AIAosYEAMGwAqHGBIxeAKLGBACZvAGhxgSu9gEAosYEAAChxgTCsAIAosYEAJq8AaHGBK72AQCixgQAwLACocYEjF4AosYEAMKwAqHGBIteAKLGBACavAGhxgSt9gEAosYEANGLAp488b4DjosBAIy2AZXsAgDR+wGJ4QEAxkWNiwEAjLYBAACK4QGOiwEAjLYBiOEBAMZFiuEBAMVFjosBAIu2AeiTAYOKBN+OAsfDAQD//wEAlCgAyMMBAICAAv3/A5Mo4+ECAJQoALe8ApMo5GEAlCgAx8MBkyiAgAIAlCgAAJMotrwCAJQoAMjDAZMogIACAJQoALa8ApMo5GEAlCgAuLwCkyjjYQCUKADIwwGTKP//AQCUKAAAgoUCtbwCx8MBAP//AQCUKADIwwEAgIAC/f8Dkyjj4QIAlCgAt7wCkyjkYQCUKADHwwGTKICAAgCUKAAAkyi2vAIAlCgAyMMBkyiAgAIAlCgAtrwCkyjkYQCUKAC4vAKTKONhAJQoAMjDAZMo//8BAJQoANWyBNq0AYl+jzsAs2G5CIwZ9g3YMgC+U7+gAYsZs2G6CIwZ9g3JQ4sZvlP0EIwZAJwqixm0YboIjBn1Dehtixn2DbkIjBn1De68A59BzXPzJgD3MgC8eAD0JgD4Mu1lu3i9HwC8eAAAu3j6PgC8eAD6Prt4uhMAvHgA",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAiMGHh0gJSQDAAMDAAMDAAMDAAUBACAHAAcHEA8HBgEkISICJQYiJygDHQQgIyQBHQQeISIBGwQcHyABGQQaHR4BFwQYGxwBFQQWGRoBEwQUFxgBER8kAwQQAA8BAAQCAAICAAICAAICABEGAAQEBwgEAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAiMGHh0gAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAgQCBQYDAiMGHh0gAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAgQCBQYDAhMGDg0QAA8BAAYEAAQEEQoIAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAg8GCgkMAAsBAAYECQoE",
      "ao": "GBgSGBIRGBgRGBERFxYXFxcWFxcWFxYXFxgWFxYXGBgRGBERGBgRGBERFxgXFxcWGBgRGBERGBcXGBcWGBcXGBcYGBgRGBERFxcXFxcWFxcWFxYXGBgRGBERGBgRGBESERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERHh4fHh8fHh4fHh8fHh4fHh8fHh4fHh8fHh4fHh8fHh4fHh8fHh4fHh8fHh4fHh8fHh4fHh8fHh4fHh8fFxgYGBgYGBgYGBcYGBcXFxgYGBgYGBgXHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHh4fHx8fHx8fHx8fHx8eHh8fHx8fHx8eHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fGxscGxwbGxscGxwcGxscGxwcGxwdGx0cHBscHBwdGxsbGxscHx8fHx8fHx8fHx8fEhIdEh0dFhYbFhsbGRkaGRoaFhYbFhsaEhIdEh0cHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "FRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGRkZGRkZGRkZGRkZGRkZGRoaGhoaGhoaGhoaGho="
    }
  ],
  "markers": []
};
