/**
 * GENERATED by scripts/import-model.ts from street-furniture-near.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../imported";

export const MODEL = lazyModel("streetFurnitureNear", () => import("./streetFurnitureNear.data"), { deferred: true });
