/**
 * GENERATED by scripts/import-model.ts from walker.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import type { ImportedModel } from "../imported";

export const KEY = "walker";

export const DATA: ImportedModel = {
  "materials": [
    {
      "role": "paint",
      "surface": "fabric",
      "tone": 1,
      "hex": "#ffffff"
    },
    {
      "role": "trousers",
      "surface": "fabric",
      "tone": 1,
      "hex": "#35404b"
    },
    {
      "role": "shoes",
      "surface": "fabric",
      "tone": 1,
      "hex": "#292b2e"
    },
    {
      "role": "hands",
      "surface": "plaster",
      "tone": 1,
      "hex": "#c99f7d"
    },
    {
      "role": "pack",
      "surface": "fabric",
      "tone": 1,
      "hex": "#6d5b47"
    },
    {
      "role": "paintskin",
      "surface": "plaster",
      "tone": 1,
      "hex": "#ffffff"
    },
    {
      "role": "hair",
      "surface": "fabric",
      "tone": 1,
      "hex": "#4a3830"
    },
    {
      "role": "eyes",
      "surface": "glass",
      "tone": 1,
      "hex": "#302d29"
    },
    {
      "role": "mouth",
      "surface": "plaster",
      "tone": 1,
      "hex": "#ad8272"
    }
  ],
  "nodes": [
    {
      "name": "WalkerBody",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.20013493299484253,
        -0.4399999976158142,
        -0.1875
      ],
      "scale": [
        0.00000610161725321687,
        0.000011902037097613381,
        0.000004615854155583468
      ],
      "triangles": 150,
      "vertices": 106,
      "positions": "xv8F/JYDyIoG0gb2xAEA14UCAPCPAQD1xAEA14UC9sQB748B1Ab1xAEA0wb2xAHdnwLUBvXEAQCE/wH2xAHtjwEA9cQBANiFAvbEAe6PAdEG9cQBAM5NjKQDkLkC08wCAKCpAdPMAgCfqQEAAL/SAtTMAgChqQHUzAIAoqkBlRaUdoTKAr22AgDmoAG7tgIA5aABAADJwQK8tgIA46ABvrYCAOSgAbWxAeJOrIYCh4UBAMhlh4UBAMdlAACLywGIhQEAx2WIhQEAyGWd3gPfXJMMmiWcAtCfAckGq6QDjhmPHucBnYEB2ULApgOkyAGODbWkA+YGnXKyogP9arAgg6QD8BnGCLqiA/u3AcoY3aMD/jekmQfApgP2rQGzfoQBwAKDAbmkA9wLqmZrgwKbjgHcowPjpwHkBpOkA+oprF6QogODjgG/DOGjA/Y89HOOpAOgI5cg66MDzCr3oQbJP6oD0GZT3boBygGJ6QLuKc9PQPCQAYr0AcTnArNzzyPt6ALwGdAj7ugC+MwBzyPt6ALvGbOCAfTpAphhygGJ6QLrKYj0AeznAu+QAdBmVN26Af4S+egC7inNTz/wkAHW4gHA6gKzc50Sl+kC8BmeEpjpAvjMAZ0Sl+kC7xnnkwGS6AKYYf4S+egC6ymnvQONVbT0AQCqVQAAALu/BACpVQC+5gGqVQAAqVUAAKpVvL8EAKlVAJqHAQAAAKpVAAAAu78EAKlVALzmAapVAACpVQAAqlW8vwQAqVUAifAEvP8DuYoD51CGA8KLAcQE+WKVA9RAuQLNb6d48GCXL+IOh2KcHYKPB8xkokf3gwG+AbwW0gntYtAEyGmXAfsRiUDCX8+UAUn7YYIl2/UE0HG/mwIAmsgCAAAAycECAJnIAgDG5gOayAIAAJnIAgAAmsgCysECAJnIAgA=",
      "index": "AAICAwQCAAEEAQICAAEEAQICAAEEAQICAAEEAQICAAERFBMBAhYCFxgVABYCFxgTABQCFRYRABICExQPABACERINAA4JAwQVFgwCDQ4LAAwCDQ4LAAwCDQ4LAAwCDQ4LAAwCDQ4LAAwJAQILDAwCDQ4LAAwCDQ4LAAwCDQ4LAAwCDQ4LAAwCDQ4LAAwJAQILEQQVAAYEAAQEEQoIIAEKAAEBAAEBCAMDCgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAg8GCgkMERADAAMFCgkBFAICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAg8GCgkMERADAAMFCgkBFAICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAg8GCgkMAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAg8GCgkMAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAwYCBwgFBAcGAgEEAwEGAgICAwQCAwYCBwgFBAcGAgEEAwEGAgICAwQCAAEEAQICAAEEAQICAAEJDAsBCAMBBgUK",
      "ao": "Hx8fHx8fHx8fHx8fHBkbHBsdHxwTHxMfHxMcHxwfHBsaHBocHx8fHx8fHx8fHx8eGhsbGhsbHB0WHBYTExYeEx4cGxwaGxoaHx8fHx8fHx8fHx8fGh0dGh0bHh8dHh0WFR0fFR8eGx0dGx0aHxsbHxseHhwcHhwfHhsaHhoeHxscHxweHhwcHhwfHhoaHhofHRoaGhwaGhodGhodGBcYGBcXFxcYGBcYFxoUFxQWFh0dFh0aHx8fHx8fHx8fHx8fHx0dHx0eHh4fHx4UHxQeHh0fHh8fGBoVGBUZFx0cFxwXHx8fHx8fHx8fHx8fHx8eHhQeHh4fHB8ZHBkcHRMTHRMZFhYTFhMTEx4ZExkTHhodHh0ZFRQTFRMTEx8ZExkTHRwZHRkZHxMTHxMZFBQTFBMTGR0dGR0ZGR0dGR0YFhkaFhoXGR0dGR0ZExMTExMTHB0eHB4eFhsZFhkXGR0dGR0ZGR0dGR0ZGR0dGR0ZExMTExMTHBweHB4eFhYcFhwYFh4fFh8fHRocHRweHB4eHRwfHR8fFRcZFRkWGx4fGx8fHhwcHh0fHh8fHx8fHx8fHx8eHx4eFxUVFxUWHx8cHxwc",
      "aoLevels": 32,
      "material": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAgICAgICAgICAgICAgICAgICAgICAgICAwMDAwMDAwMDAwMDAwMEBAQEBAQEBAQE"
    },
    {
      "name": "WalkerHead",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.14810092747211456,
        -0.14800000190734863,
        -0.1640000194311142
      ],
      "scale": [
        0.000004519750363058945,
        0.000004765697854183864,
        0.000004684520120650559
      ],
      "triangles": 77,
      "vertices": 55,
      "positions": "gIAEAIKjBACQjgGH3QLsmgIAtoMB65oCjtcC/5MCAJDXAsqQAeyaAgC2gwGWdY/XApFagZADoOUD5LMC2uACrbwG1k0Anq4FAI6SAY/XApYg69UCjdcC0swBAJ6uBQCCQY/XAqSCAfv6Ao3XAqOCAQCergUAgUGP1wKkggHbggGQ1wKL7wIAna4FAI2SAY7XApYg5mIAz6EDlnWN1wKSWgCergUA7poC28kEiecBAMzyAaVihqsDALbGAbk256UB8inL9ALiogT5VQDmnQHS9AL6rQLlnQGr6AHGzwH5/AKu/AH5hAH6/AL0PvvQAQDq/AG02ALnygL/3gG1uAKcmwGMnwKT7wLMrwGLQP0fy68BjED9sAHMrwH1vAK3hwHnygLqHb4CkTLdXMbPAfr8Aq38AYt9+fwCnWC6NuelAfIpgLMBqsMB1o8GiEwAAACQSACHTAAAkrcCj0gAiEwAAACQSACHTAAA4bMB0a0C1RC6fAAAAKwnALl8AAA=",
      "index": "AAICAgICAwQCCQQGCQoHBAYDCQQMAwEIBQYCDwgIDxADBQQEERAGAQEGAwQCCQQGCQoDAwMKFxYGAQEGAwQCCQQGCQoDAwkQAA8UIRwIAwEEAQIECQQGCQoBAAICAwQCBxMeKyQGAwMKBQYDAgEhJCMDKh0FByonJgQjIB8BKAICAwQCAgICCQYECQoHAgEKAQEGAAUIAgMCAgEEAwcOAQMGAQICAQ0SAQEEAQICAgEBAAYCBwgDBgUEBxEYAgEZHBsFJAEhJCMBIhcBBgkIAAQEBwgFGgICAwQCAgICAwQCAgICAwQC",
      "ao": "FB4dExMTExMTHxMTHxMfExMTFB0dExMTExMeHxMfHx8fExMTFB0dHxMTHxMfHx8fHx8fExMTFB0dHhMTHhMeHx8fHx8fExMTExMTFB0dHxMTHxMfHx8fHx8eHx8THxMeExMTFB0dHhMTHhMTHxMTHxMfExMTFB0eExMTExMTHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYHBwcHCAg="
    }
  ],
  "markers": []
};
