/**
 * GENERATED by scripts/import-model.ts from walker.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import type { ImportedModel } from "../imported";

export const KEY = "walker";

export const DATA: ImportedModel = {
  "materials": [
    {
      "role": "paint",
      "surface": "fabric",
      "tone": 1,
      "hex": "#ffffff"
    },
    {
      "role": "trousers",
      "surface": "fabric",
      "tone": 1,
      "hex": "#35404b"
    },
    {
      "role": "shoes",
      "surface": "fabric",
      "tone": 1,
      "hex": "#292b2e"
    },
    {
      "role": "hands",
      "surface": "plaster",
      "tone": 1,
      "hex": "#c99f7d"
    },
    {
      "role": "paintskin",
      "surface": "plaster",
      "tone": 1,
      "hex": "#ffffff"
    },
    {
      "role": "hair",
      "surface": "fabric",
      "tone": 1,
      "hex": "#4a3830"
    },
    {
      "role": "eyes",
      "surface": "glass",
      "tone": 1,
      "hex": "#302d29"
    },
    {
      "role": "mouth",
      "surface": "plaster",
      "tone": 1,
      "hex": "#ad8272"
    }
  ],
  "nodes": [
    {
      "name": "WalkerBody",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.21493378281593323,
        -0.4399999976158142,
        -0.10000000149011612
      ],
      "scale": [
        0.000006615199694928528,
        0.000011902037097613381,
        0.0000032806897623602454
      ],
      "triangles": 146,
      "vertices": 102,
      "positions": "9OYF/JYD2KYFkgb2xAEAr/EBALbKAQD1xAEAr/EB9sQBtcoBkgb1xAEAkQb2xAHplAOSBvXEAQCe6wH2xAG1ygEA9cQBALDxAfbEAbbKAZEG9cQBAMxHjKQDxrgD6bICAJLuAemyAgCR7gEAAKHcA+qyAgCR7gHqsgIAku4BuRSUdq7QA6+eAgCe4gGvngIAneIBAAC5xAOwngIAneIBsJ4CAJ7iAdGjAeJOjvEC3XoA8I4B3XoA744BAADhnQLeegDvjgHeegDwjgGXvATNV8yYAsMPqQGB6QG5KtOkA+RByAyKAdC8AdiGAZSeA9vjArU+z6MDilXajgHOoQOqVdtNn6MD0DTGFranA4CaAZlDg6QDog3UxAWGoAOxywKycswE2SryMpOkA4BSy1zbA8gi8GCGrAOIWrAo96QD0irVePaiA+B/1jfHpAOYCrmgAZKfA71v0EvDowO8HYmYBaU+43zSXlPbhgK8AYnpAvI6t0lA6ssBkOEBxOcCraIB7SDt6AKyJO4g7ugCrKAC7SDt6AKxJKV49OkC3ogBvAGJ6QLvOo7hAeznAuvLAdReVNuGAsIR+egC8jq3ST/qywGK0QHA6gKtogHnEJfpArIk6BCY6QKsoALnEJfpArEkq4gBkugC3ogBwhH56ALvOt2aA41V8NcCAKpVAAAA06kGAKlVAMrUAapVAACpVQAAqlXUqQYAqVUA3HwAAACqVQAAANOpBgCpVQDK1AGqVQAAqVUAAKpV1KkGAKlVAN/HBc6CBMHlAu1GAPGOAaoC/WLwF9g4AKhyxAvgXbeYAuML92GqNNJS+GHIWvkZ92HgF6y9Bvhh0aYBxkaeBaCOAakC/WLwF7c4lwTlcYsMlmfo6AHsC/1i2QSxUuBdxYkB+hn3YeAX",
      "index": "AAICAwQCAAEEAQICAAEEAQICAAEEAQICAAEEAQICAAERFBMBAhYCFxgVABYCFxgTABQCFRYRABICExQPABACERINAA4JAwQVFgwCDQ4LAAwCDQ4LAAwCDQ4LAAwCDQ4LAAwCDQ4LAAwJAQILDAwCDQ4LAAwCDQ4LAAwCDQ4LAAwCDQ4LAAwCDQ4LAAwJAQILEQQVAAYEAAQEEQoIIAEKAAEBAAEBCAMDCgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAg8GCgkMERADAAMFCgkBFAICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAg8GCgkMERADAAMFCgkBFAICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAg8GCgkMAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAg8GCgkMAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIBwEGAwQEAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIBwEGAwQE",
      "ao": "Hx8fHx8fHx8fHx8fHRsbHRscHx8fHx8fHx8fHx8fHBsbHBsbHx8fHx8fHx8fHx8fHBscHBwcHx8fHx8fHx8fHx8fGxoaGxobHx8fHx8fHx8fHx8fGx0dGx0cHx8fHx8fHx8fHx8fGh0dGh0aHxsbHxseHhwcHhwfHhsaHhoeHxscHxwfHhwcHhwfHhoaHhoeHRoaGhwaGhodGhodGBcYGBcXFxcYGBcYHx8fHx8fHx8fHx8fHBgaHBocGhobGhsZHx8fHx8fHx4UFB4eFB4fGh4fGh8eHx8fHx8fHx8fHx8fHhYdHh0eExQYExgZHBkeHh8eHh4cHB4ZHBkcHhMTHhMZFhYTFhMTEx4ZExkTHhwdHh0ZFRQTFRMTEx8ZExkTHRwZHRkZHhMTHhMZFBUTFBMTGR0dGR0ZGR0dGR0YFhkaFhoXGR0dGR0ZExMTExMTHB0eHB4eFhsZFhkWGR0dGR0ZGR0dGR0ZGR0dGR0ZExMTExMTHRweHR4eHh8fHh8fHh4fHh8fGxYaGxocFh0dFh0bHh8eHh4eHhsfHh8fGhUfGh8fExocExwdGRwdGR0aHh8eHh4e",
      "aoLevels": 32,
      "material": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAgICAgICAgICAgICAgICAgICAgICAgICAwMDAwMDAwMDAwMDAwMDAwMDAwM="
    },
    {
      "name": "WalkerHead",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.14810092747211456,
        -0.14800000190734863,
        -0.1640000194311142
      ],
      "scale": [
        0.000004519750363058945,
        0.000004765697854183864,
        0.000004684520120650559
      ],
      "triangles": 77,
      "vertices": 55,
      "positions": "gIAEkI4B+sUBAI7XAsmQAYKQAwDuuQGVdY3XApJa65oCnq4FtYMBAJCOAYjdAuyaAo+OAdHZAeuaAq28BtLZAdrgApCOAdZNAJ6uBQCOkgGP1wKWIOvVApDXAtLMAQCdrgUAgkGO1wKkggH9uwMAAIJBjdcCo4IBAJ6uBQDr1QKP1wLRzAGOkgGN1wKVIACergUApy+P1wK5gQOWdY3XApJaAJ6uBQDumgKP1wKvyQIA+vwCrpoB+q0CAKaMAYx9+fwCnWCFqwPL8gGPZMz0AuRMgo4By/QCyMAF2J4CwP0D35oEghT5hAH6/AL0PriHAefKAuods9gC6MoCgN8B/h/LrwGMQJPvAsyvAYtA/R/LrwGMQP2wAcyvAfW8AreHAefKAuodvgKRMt1cxs8B+vwCrfwBi335/AKdYLo256UB8imAswGqwwHWjwaITAAAAJBIAIdMAACStwKPSACITAAAAJBIAIdMAADhswHRrQLVELp8AAAArCcAuXwAAA==",
      "index": "AAICAwQCAgICAg0GAwYECQoHCgcKCwgGDQ4CDQEQDQ4DAwEIAAcMBwIIAwEEAQIECQQGCQoBAAICAwQCBwsWEQoGAwMKBQYDAgEGAwQCAxUcFxAGBwQGCQoDAgEGAwQCAxsiHRYGBwQGCQoDAgElKCcBLCEBBhwpKAQjIB8FLAICAwQCAgcGAgEEBwoHBgMICQgEAgEEAQICBQMIAgEEAQICBQcMAgEEAQICBQsQBAEBAAYCBwgDBgUEBw8WABUJIgEfIiEBJgEjJiUIBgcBAAwCDQ4DGgICAwQCAgICAwQCAgICAwQC",
      "ao": "HxMTHxMfExMTFB4dExMTExMTFB0dExMTExMeHxMfHx8fExMTExMTFB0dHxMTHxMfHx8fHx8fHx8fHx8fExMTFB0dHhMTHhMeHx8fHx8eExMTFB0dHxMTHxMfHx8THxMeExMTFB0dHhMTHhMTHxMTHxMfExMTFB0eExMTExMTHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUGBgYGBwc="
    }
  ],
  "markers": []
};
