/**
 * GENERATED by scripts/import-model.ts from apartment-low-near.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../imported";

export const MODEL = lazyModel("apartmentLowNear", () => import("./apartmentLowNear.data"), { deferred: true });
