/**
 * GENERATED by scripts/import-model.ts from building-tower-spire-near.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../imported";

export const MODEL = lazyModel("buildingTowerSpireNear", () => import("./buildingTowerSpireNear.data"), { deferred: true });
