/**
 * GENERATED by scripts/import-model.ts from building-midrise-mech-near.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../imported";

export const MODEL = lazyModel("buildingMidriseMechNear", () => import("./buildingMidriseMechNear.data"), { deferred: true });
