/**
 * GENERATED by scripts/import-model.ts from building-house.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import type { ImportedModel } from "../imported";

export const KEY = "buildingHouse";

export const DATA: ImportedModel = {
  "materials": [
    {
      "role": "plinth",
      "surface": "concrete",
      "tone": 1,
      "hex": "#bdb6aa"
    },
    {
      "role": "core",
      "surface": "plaster",
      "tone": 1,
      "hex": "#ece3d4"
    },
    {
      "role": "wall",
      "surface": "plaster",
      "tone": 1,
      "hex": "#ece3d4"
    },
    {
      "role": "window",
      "surface": "glass",
      "tone": 1,
      "hex": "#636a72"
    },
    {
      "role": "trim",
      "surface": "stone",
      "tone": 1,
      "hex": "#f6efe2"
    },
    {
      "role": "door",
      "surface": "timber",
      "tone": 1,
      "hex": "#5e514a"
    },
    {
      "role": "roof",
      "surface": "slate",
      "tone": 1,
      "hex": "#8d8c8c"
    },
    {
      "role": "wallSoft",
      "surface": "plaster",
      "tone": 1,
      "hex": "#dbd3c6"
    },
    {
      "role": "roofLight",
      "surface": "slate",
      "tone": 1,
      "hex": "#a9a6a0"
    }
  ],
  "nodes": [
    {
      "name": "Building",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.49720001220703125,
        0,
        -0.5
      ],
      "scale": [
        0.000015173571746609636,
        0.0000156404970803104,
        0.00001586938309998737
      ],
      "triangles": 316,
      "vertices": 224,
      "positions": "7hYA/r8HotIHAAAA+iwAodIHAAAAAK+nB6LSBwAAAPksAKHSBwAA+EL6LLDnBrLMBgAAALLoBACxzAYAAAAAr6cGsswGAAAAsegEALHMBgAAlykA4s4GlIIDAAAA5OABAJOCAwAAzpwE4+ABAJSCAwAAAOTgAQCTggMAAL2wAwAAAOqkAQCPbAAAlpsC6aQBAP5m6qQBAP1mAAC26ALppAEAAOqkAQD9ZgAAhJYC6aQBAJBs6qQBAI9sAACQbOTiAQDhngcAAJBs4+IBxR2GrwEAAIWvAemkAQCGrwEAAP5m6qQB8Ae6mgEAALmaAc2FAwC6mgEAAP5mzoUD7weGrwEAAIWvAemkAQCGrwEAAJBs4+ABy9gG4Z4HAAAA5OABAOKeBwAA86kBAAAA6qQBAPSpAQAA+9gC6aQBAOnsAQAAAOqkAQDq7AEAAPGbA+mkAQDzqQHqpAEA9KkBAADzqQHk4gEA4p4HAADzqQHj4gHEHYevAQAAiK8B6aQBAIevAQAA6ewB6qQBAIevAQAAiK8B6aQBAIevAQAA7vQF4+ABgIAEAObWAQAAAM7YAgDqqQHN2AIAAM7YAgDi5wHN2AIAsegE9cQBAObWAQAA6qkBAADi5wEAAMuRA83YAgDqqQEA8R4AxJ0EAAD1xAEA6akB9sQBAAD1xAHyHqqaBbpi4Z4Hj/EGuWIA5tYBAAAAzdgCAOqpAc7YAgAAzdgCAOLnAc7YAgCx6AT2xAEA5tYBAADqqQEAAOLnAQAAy5EDztgCAOqpAQDyHgDDnQQAAPbEAQDpqQH1xAEAAPbEAfEeqpoFu2LiX6mmBd7QA+LHAQAAAP4NAOHHAQAA4scBANMV4ccBAAAA/Q0A4scBAADazwIA1BXixwEAAAD+DQDhxwEAAOLHAQDTFeHHAQAAAP0NAOLHAQAA4z0A54sH4ccBAAAA/g0A4scBAADhxwEA1hXixwEAAAD9DQDhxwEAAJHUAQDVFeHHAQAAAP4NAOLHAQAA4ccBANYV4scBAAAA/Q0A4ccBAADwlwb9CaypBAAAxdwBAP4NAAAAxtwB0xYAxdwBAADG3AEA/Q0AAADF3AG1tQcAAAAAxtwBAP4NAAAAxdwB1BYAxtwBAADF3AEA/Q0AAADG3AGXKdD6AoL+ApLxBwAAAPonAJHxBwAAkvEH3o0CpewDAPwbAAC1QYp7AP8LAAC1QYp7AP8LAAC3QYp7AP0LAJHxBwAAAP4LAAC4QYl7AIAMAAC2QYl7AIAMAAC2QYl7APsbAADdjQKl7AOS8QcAAAD5JwCR8QcAAJLxB7JpinsA/gsAALhBinsAgAwAALZBiHsAgAwAkfEHAAAA/wsAALVBh3sA/wsAALdBiXsA/QsA6NAFnJoCxN0BlpABAAAA/hMAlZABAAAAAOuJAZaQAQAAAP0TAJWQAQAA59MCuZsEnLEGkvcBAAAA/BMAkfcBAAAAAM1YkvcBAAAA+xMAkfcBAACi4wKmpQLD3QSicQAAAJT2AQChcQAAAACnbKJxAAAAk/YBAKFxAADX5wW2tAGUtgL+/wcAAADiH7En/f8HAAD+/wfhH68n/f8HAAD+/wfmC7An/f8HAAA=",
      "index": "AAICAwQCAgICAwQCAwUBCAcKAg0GCAcCAQEGAwQBCAICAwQCAgICAwQCAwUBCAcKAg0GCAcCCAICAwQCAgICAwQCBwoCCwwCAhEUAQICCw4CDxACAhUYAQICERAEExQCAgITEhEHHgMZHh0BBgQUFxgEAgIVFBMHIAMbIB8VBhgWLS4EAgIXFhUHIgMdIiEBBgQYGxwEAgICAwQCAAICAwQCAgICAwQCAhEUAQICDQwEDxACAgINDAsJGgMVGhkBBgYOExQEAgIPDg0HGgMVGhkBBgQQExQEZ2oCa2wCAAEEAQICAAEEAQJVTAwCDQ4LBAoCCwwHAjtEBwgFAAYCBwgFAAYnIiEkBgIJCAcJFgMRFhUDDAIKCwwEAmtWCCMyFQgOTVACUVICAAEEAQICAAEEAQI/NgwCDQ4LBAoCCwwHAqEBqgEHCAUABgIHCAUABoEBfHt+BgIJCAcJFgMRFhUDDAIKCwwEAlVACH2MARUIDoUBAgMCAQEUAgMCAQEsAgMCAQEMAgMCAQEkAgMCAQEmAgMCAQGdAQYcISIBiAECAgMEAgABBAECAgICCwoJAQwLBgYFBAEDAQYFDKkBBiAlJgGIAQICAwQCAAEEAQICAgILCgkBDAsGBgUEAQMBBgUMiQEGGB0eAXACAgMEAgABBAECAgICCwoJAQwLBgYFBAEDAQYFDJEBBhgdHgF4AgIDBAIAAQQBAgICAgsKCQEMCwYGBQQBAwEGBQx/DBAbHAFoAgIDBAIAAQQBAgICAgsKCQEMCwYGBQQBAwEGBQxtDBAbHAFWAgIDBAIAAQQBAgICAgsKCQEMCwYGBQQBAwEGBQwCAgIDBAIDBgIAAgIAAgIAAgIAEQEACAQEBBMMBA8BBhIAAgIAAgIAAgIAAiUAGAQEBCMAHAQIAgIDBAIBAQYAAgIAAgIAAi8AASQABAQELSIACAQJBwEAGAIAAgIAAgIAHQYACRoEBBcQBBMaAgIDBAICAgIDBAIDBQEIBwoCDQYIBwIBAQYDBAEGAQkMCwEQAgIDBAICAgIDBAIDBQEIBwoCDQYIBwIBAQYDBAEGAQkMCwG3AgIDAgEB6gEBEg8QAgABAQQDBgAFAQgHCgAJAQwLDgANARAPEgARARQTFgAVARgXGiIVBRwbARwRARQTFgMNARAPEgMJAQwLDgMFAQgHCgMBAQQDBhkZMBUWAhUdBSQjAS4BIyYlHkICAgMEAgICAgMEAgMFAQgHCgINBggHAggCAgMEAgABBAECAgIDAwgHAQEGCAcEBA==",
      "ao": "GBgZGBkZGRkYGRgYGRkYGRgYGBgZGBkZHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcGBgdGB0dGBkdGB0cHRoeHR4fGh0bGhseHBseHB4bGx0eGx4fHx4RHxERExQWExYWFBMXFBcVFhcUFhQUExQWExYWFBQVFBUVFRUUFRQUFBMWFBYWFBQXFBcWFRcUFRQUGBgdGB0dHRseHR4eGxsfGx8eGx0eGx4eHh4RHhERFBQWFBYWFBQXFBcWFRcUFRQTFBMWFBYWFBQYFBgVFRcUFRQUGRgbGRsdHRsfHR8fHx8fHx8RGBgbGBsbHx8fHx8fGBgcGBwbGxwfGx8fHx8RHxEfExQXExcXFBQXFBcVFRcUFRQUFhEfHxEWHx8WGBgbGBsdHRsfHR8eHh8fHh8RGBgbGBsbHx8fHx8fGBgdGB0bGx0eGx4fHx4RHxEfExMWExYWFBQXFBcWFhcUFhQUFhEfHxEWHx8WFRUVFRUUFBQVFBUVFBQVFBUVFRQUFRQUFBUUFBQUFBQVFBUVFxYUFxQUHRwdHR0cGBcWGBYXExMTExMTFxgYFxgXFhcWFhYWFhcTFhMUHBwdHB0cFxgXFxcXExMTExMTFhcXFhcWFxkYFxgXGBcUGBQUHBwcHBwdGBgYGBgXExMTExMUFhgYFhgWFxcXFxcWGBcUGBQTHRwcHRwdGBgXGBcXExMTExMTFxcXFxcXFxcYFxgXGBgUGBQUHBwdHB0cGRkYGRgYExMTExMTFxcYFxgXFxcXFxcXGBgUGBQUHBwdHB0dGRkYGRgYExMTExMTFxcXFxcXFxgXFxcWHx8fHx8fHx8UFB8fHx8fHx8fHx8fHxQfHx8fHx8fHx8fHx8fHx8fHx8UFB8fHx8fHxQfHx8fHx8fHx8fHx8fHx8fHx8fHx8UFB8fHx8fHxQfHx8fHx8UFB8fHx8fHx8fHx8fHxQfHx8fHx8fGRobGRsbHh4eHh4eHh0cHhwdHBsbHBscHx8fHx8fFRcUFRQTHx8fHx8fERERERERFxkaFxoXGBobGBsYGhkVGhUWGBcZGBkZFRQUFRQVHx8bHxsbGxsdGx0dHx8cHxwbHBweHB4dHx8cHxwcGxseGx4dHx8RHxERGxwfGx8fHR0bHRsbGxseGx4fHR0bHRsbGxoeGx4fHhwbHhsbEREeER4fGBgbGBsaGxsYGxgYFxYTFxMTGBcRGBERFhYRFhERERgUERQVHx8fHx8fHx4fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "AAAAAAAAAAAAAAEBAQEBAQEBAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDAwMDAwMDAwMDAwMEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFBQYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYHBwcHBwcHBwcHBwcICAgICAgICA=="
    }
  ],
  "markers": [],
  "meta": {
    "windows": [
      {
        "facing": "+z",
        "u": -0.26,
        "v": 0.3525,
        "w": 0.17,
        "h": 0.165,
        "plane": 0.414
      },
      {
        "facing": "+z",
        "u": 0.26,
        "v": 0.3525,
        "w": 0.17,
        "h": 0.165,
        "plane": 0.414
      },
      {
        "facing": "-z",
        "u": -0.2,
        "v": 0.3525,
        "w": 0.17,
        "h": 0.165,
        "plane": 0.414
      },
      {
        "facing": "-z",
        "u": 0.2,
        "v": 0.3525,
        "w": 0.17,
        "h": 0.165,
        "plane": 0.414
      },
      {
        "facing": "+x",
        "u": 0,
        "v": 0.345,
        "w": 0.2,
        "h": 0.17,
        "plane": 0.414
      },
      {
        "facing": "-x",
        "u": 0,
        "v": 0.345,
        "w": 0.2,
        "h": 0.17,
        "plane": 0.414
      }
    ],
    "roofPads": [],
    "maxProps": 0
  }
};
