/**
 * GENERATED by scripts/import-model.ts from civic-kit-near.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../imported";

export const MODEL = lazyModel("civicKitNear", () => import("./civicKitNear.data"), { deferred: true });
