/**
 * GENERATED by scripts/import-model.ts from power-station.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../imported";

export const MODEL = lazyModel("powerStation", () => import("./powerStation.data"));
