/**
 * GENERATED by scripts/import-model.ts from power-station-near.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../imported";

export const MODEL = lazyModel("powerStationNear", () => import("./powerStationNear.data"), { deferred: true });
