/**
 * GENERATED by scripts/import-model.ts from transit-station-near.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../imported";

export const MODEL = lazyModel("transitStationNear", () => import("./transitStationNear.data"), { deferred: true });
