/**
 * GENERATED by scripts/import-model.ts from village-chapel-near.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../imported";

export const MODEL = lazyModel("villageChapelNear", () => import("./villageChapelNear.data"), { deferred: true });
