/**
 * The committed reference analyses (PLAN.md sections 30 and 59).
 *
 * Each file is a real `RepoAnalysis` captured from `/api/analyze` against the
 * live GitHub API. They are the demo's safety net: when GitHub rate-limits the
 * hosted app and `FIXTURE_FALLBACK` is on, the route serves these instead
 * (`lib/github/fixtures.ts`).
 *
 * This test is the contract between the captured data and the world layer: if
 * a fixture stops parsing, or the generator stops accepting one, the fallback
 * would fail in front of voters rather than here.
 */

import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import type { RepoAnalysis } from "@/types/analysis";
import {
  buildingsOnRoads,
  generateCity,
  obstructedPlots,
  overlappingBuildings,
} from "@/lib/city/generator";
import { SETTLEMENT_PARAMS } from "@/lib/city/settlement";

const DIR = path.join(process.cwd(), "fixtures");

const files = readdirSync(DIR)
  .filter((name) => name.endsWith(".analysis.json"))
  .sort();

/** The reference set of PLAN.md section 59, which must stay committed. */
const REQUIRED = [
  "atom__atom.analysis.json",
  "facebook__react.analysis.json",
  "honojs__hono.analysis.json",
  "microsoft__vscode.analysis.json",
  "react__react.analysis.json",
  "sindresorhus__p-limit.analysis.json",
  "vercel__turborepo.analysis.json",
];

/** Generated by scripts, not captured: `scripts/make-backlog-fixture.ts` and S9's stress fixture. */
const SYNTHETIC = new Set(["backlog.analysis.json", "stress.analysis.json"]);

describe("committed analysis fixtures", () => {
  it("covers the reference repository set", () => {
    for (const name of REQUIRED) expect(files).toContain(name);
  });

  it.each(files)("%s parses and builds a city inside the section 37 limits", (name) => {
    const raw = readFileSync(path.join(DIR, name), "utf8");
    const synthetic = SYNTHETIC.has(name);
    // Section 34: the response stays compact. Section 76.6 amends it to "300 KB
    // plus the backlog, hard ceiling 1 MB". The captured giants (react, vscode)
    // carry a real backlog now, so every file answers to the ceiling, and a
    // captured one still keeps everything but its backlog under 300 KB.
    expect(raw.length).toBeLessThan(1_000_000);

    const analysis = JSON.parse(raw) as RepoAnalysis;
    if (!synthetic) {
      const { issues, pulls } = analysis.metrics;
      const withoutBacklog = {
        ...analysis,
        metrics: {
          ...analysis.metrics,
          issues: { ...issues, backlog: undefined },
          pulls: { ...pulls, backlog: undefined },
        },
      };
      expect(JSON.stringify(withoutBacklog).length).toBeLessThan(300_000);
    }
    expect(analysis.repo.fullName).toContain("/");
    expect(analysis.districts.length).toBeGreaterThan(0);
    expect(analysis.buildings.length).toBeGreaterThan(0);
    // The route rewrites this to "fixture" when it serves the fallback; a
    // captured file records how it was captured. `sample.analysis.json` is the
    // hand-written W0 fixture and is honestly marked "fixture", as are the
    // generated synthetic ones.
    expect(analysis.source).toBe(
      name === "sample.analysis.json" || synthetic ? "fixture" : "live",
    );

    const city = generateCity(analysis);
    // Section 37's limits, per settlement tier (76.5).
    const limits = SETTLEMENT_PARAMS[city.settlement!.tier];
    expect(city.buildings.length).toBeLessThanOrEqual(limits.buildings.max);
    expect(city.props.trees.length).toBeLessThanOrEqual(limits.trees);
    expect(city.vehicles.count).toBeLessThanOrEqual(limits.vehicles.max);
    expect(city.incidents.length).toBeLessThanOrEqual(limits.heroes.incidents);
    expect(city.constructionSites.length).toBeLessThanOrEqual(limits.heroes.sites);
    expect(city.landmarks.length).toBeGreaterThan(0);

    // The geometric invariants hold for real repositories, not just the
    // hand-written sample.
    expect(overlappingBuildings(city)).toEqual([]);
    expect(buildingsOnRoads(city)).toEqual([]);
    expect(obstructedPlots(city)).toEqual([]);

    // Every district is somewhere a user can go: it has a rect and buildings.
    for (const district of city.districts) {
      expect(district.rect.w).toBeGreaterThan(0);
      expect(district.rect.d).toBeGreaterThan(0);
    }
  });
});
