/**
 * GENERATED by scripts/import-model.ts from crowd-forms.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import type { ImportedModel } from "../models/imported";

export const KEY = "crowd";

export const DATA: ImportedModel = {
  "materials": [
    {
      "role": "paintB",
      "surface": "metal",
      "tone": 1,
      "hex": "#fefefe"
    },
    {
      "role": "carGlass",
      "surface": "glass",
      "tone": 1,
      "hex": "#4c5c6c"
    },
    {
      "role": "tyre",
      "surface": "fabric",
      "tone": 1,
      "hex": "#262729"
    },
    {
      "role": "hazard",
      "surface": "glass",
      "tone": 1,
      "hex": "#ffae3a"
    },
    {
      "role": "paintA",
      "surface": "metal",
      "tone": 1,
      "hex": "#ffffff"
    },
    {
      "role": "warnTri",
      "surface": "metal",
      "tone": 1,
      "hex": "#c8493c"
    },
    {
      "role": "scorch",
      "surface": "concrete",
      "tone": 1,
      "hex": "#2b2724"
    },
    {
      "role": "burnt",
      "surface": "concrete",
      "tone": 1,
      "hex": "#4a433d"
    },
    {
      "role": "lug",
      "surface": "metal",
      "tone": 1,
      "hex": "#3b3632"
    },
    {
      "role": "flameOuter",
      "surface": "metal",
      "tone": 1,
      "hex": "#ff8a2a"
    },
    {
      "role": "flameInner",
      "surface": "metal",
      "tone": 1,
      "hex": "#ffd35a"
    },
    {
      "role": "band",
      "surface": "timber",
      "tone": 1,
      "hex": "#eeeae1"
    },
    {
      "role": "beacon",
      "surface": "metal",
      "tone": 1,
      "hex": "#ff3b30"
    },
    {
      "role": "flagPole",
      "surface": "metal",
      "tone": 1,
      "hex": "#6b6f6c"
    },
    {
      "role": "flag",
      "surface": "fabric",
      "tone": 1,
      "hex": "#5e9a6a"
    },
    {
      "role": "gate",
      "surface": "metal",
      "tone": 1,
      "hex": "#5c6266"
    },
    {
      "role": "dirt",
      "surface": "concrete",
      "tone": 1,
      "hex": "#8d7a5e"
    },
    {
      "role": "notice",
      "surface": "metal",
      "tone": 1,
      "hex": "#eeeae2"
    },
    {
      "role": "hoardPost",
      "surface": "metal",
      "tone": 1,
      "hex": "#4a4f4c"
    },
    {
      "role": "paintA",
      "surface": "timber",
      "tone": 1,
      "hex": "#ffffff"
    },
    {
      "role": "paintA",
      "surface": "timber",
      "tone": 0.8,
      "hex": "#ffffff"
    },
    {
      "role": "board",
      "surface": "metal",
      "tone": 1,
      "hex": "#d8392f"
    },
    {
      "role": "workerLegs",
      "surface": "fabric",
      "tone": 1,
      "hex": "#35404b"
    },
    {
      "role": "worker",
      "surface": "fabric",
      "tone": 1,
      "hex": "#e6c02f"
    },
    {
      "role": "workerSkin",
      "surface": "plaster",
      "tone": 1,
      "hex": "#c99f7d"
    },
    {
      "role": "workerHelmet",
      "surface": "metal",
      "tone": 1,
      "hex": "#f0d44a"
    },
    {
      "role": "asphalt",
      "surface": "concrete",
      "tone": 1,
      "hex": "#6a6860"
    },
    {
      "role": "hole",
      "surface": "concrete",
      "tone": 1,
      "hex": "#2f302c"
    },
    {
      "role": "rubble",
      "surface": "concrete",
      "tone": 1,
      "hex": "#4a4740"
    },
    {
      "role": "coneOrange",
      "surface": "metal",
      "tone": 1,
      "hex": "#e8853d"
    },
    {
      "role": "coneBand",
      "surface": "metal",
      "tone": 1,
      "hex": "#f2efe7"
    },
    {
      "role": "weed",
      "surface": "foliage",
      "tone": 1,
      "hex": "#88a46a"
    },
    {
      "role": "barrierRed",
      "surface": "metal",
      "tone": 1,
      "hex": "#c8493d"
    },
    {
      "role": "barrierWhite",
      "surface": "metal",
      "tone": 1,
      "hex": "#f2efe6"
    },
    {
      "role": "trestle",
      "surface": "metal",
      "tone": 1,
      "hex": "#50544f"
    },
    {
      "role": "amber",
      "surface": "metal",
      "tone": 1,
      "hex": "#ffb347"
    },
    {
      "role": "steel",
      "surface": "metal",
      "tone": 1,
      "hex": "#9aa0a6"
    },
    {
      "role": "plank",
      "surface": "timber",
      "tone": 1,
      "hex": "#c39a5f"
    },
    {
      "role": "netting",
      "surface": "fabric",
      "tone": 1,
      "hex": "#8b917f"
    },
    {
      "role": "signPost",
      "surface": "metal",
      "tone": 1,
      "hex": "#6b6f6b"
    },
    {
      "role": "signBlue",
      "surface": "metal",
      "tone": 1,
      "hex": "#3f74b5"
    },
    {
      "role": "signWhite",
      "surface": "metal",
      "tone": 1,
      "hex": "#eeeae0"
    },
    {
      "role": "tripod",
      "surface": "timber",
      "tone": 1,
      "hex": "#c9a24a"
    },
    {
      "role": "instrument",
      "surface": "metal",
      "tone": 1,
      "hex": "#e2c46a"
    },
    {
      "role": "lens",
      "surface": "glass",
      "tone": 1,
      "hex": "#2f3330"
    },
    {
      "role": "staffRed",
      "surface": "metal",
      "tone": 1,
      "hex": "#d8392e"
    },
    {
      "role": "peg",
      "surface": "timber",
      "tone": 1,
      "hex": "#b59a6f"
    },
    {
      "role": "tape",
      "surface": "fabric",
      "tone": 1,
      "hex": "#ff6f91"
    },
    {
      "role": "earth",
      "surface": "concrete",
      "tone": 1,
      "hex": "#6e5540"
    },
    {
      "role": "shoring",
      "surface": "timber",
      "tone": 1,
      "hex": "#9c7a4e"
    },
    {
      "role": "rail",
      "surface": "concrete",
      "tone": 1,
      "hex": "#cfcabd"
    },
    {
      "role": "boardPost",
      "surface": "metal",
      "tone": 1,
      "hex": "#6b6f6e"
    },
    {
      "role": "vanWhite",
      "surface": "metal",
      "tone": 1,
      "hex": "#e9e6dc"
    },
    {
      "role": "glass",
      "surface": "glass",
      "tone": 1,
      "hex": "#3b4450"
    },
    {
      "role": "chassis",
      "surface": "metal",
      "tone": 1,
      "hex": "#2f3134"
    },
    {
      "role": "glassDark",
      "surface": "glass",
      "tone": 1,
      "hex": "#2d3337"
    },
    {
      "role": "crazed",
      "surface": "glass",
      "tone": 1,
      "hex": "#dfe8ea"
    },
    {
      "role": "rust",
      "surface": "metal",
      "tone": 1,
      "hex": "#80573d"
    },
    {
      "role": "bumper",
      "surface": "metal",
      "tone": 1,
      "hex": "#3d4045"
    },
    {
      "role": "cone",
      "surface": "metal",
      "tone": 1,
      "hex": "#e8853c"
    },
    {
      "role": "oil",
      "surface": "concrete",
      "tone": 1,
      "hex": "#3f3b35"
    },
    {
      "role": "tuft",
      "surface": "foliage",
      "tone": 1,
      "hex": "#8aa46a"
    }
  ],
  "nodes": [
    {
      "name": "Collision",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -1.1031365394592285,
        0,
        -1.499144196510315
      ],
      "scale": [
        0.000032784020754295434,
        0.000014190890473068702,
        0.000042857986989206476
      ],
      "triangles": 141,
      "vertices": 125,
      "positions": "0NoHnNwBqroBwgmugQMuhAmIN9RQ3wS75AMX8TPa4QWjUoYJjm7SUJnDAo1u1VzNL6W0AukBwROIN8hPzC+s6wLqAcUS4aMGgVGjGIUssE+UmAO85AP0jgPhBLvkAxfHgQPozwbfDtzWAgCODceBA+fPBt8O4QS85AMX2KsDgxaqrQHfBLfOAxXnF8CQBHWtmQOHQtMPyByIQowB5xe/kAR17I8DprQCquoB4QShkwIXpyGs6wKhAdfDAgCxDIkmiVi7AeAEoZMCGOO0AdbABf3JB7GmAgDgVMgXjm72TpTBAgC7XM4sq+sC6wzWgwGs6wKO8wLOLKvrAusM08oEAI3wAaawAQCi5gLMLKzrAusM/C2b5wHmhgHs5AIA3WbThwKXuwHrtgTN/wIAuG625wPJ3QTGjwYAtKIDAIYJAK+KAQCzogMAwNIDtKID7hEAs6IDAIcJtKIDsIoBALOiAwCXsAMAl54EALSiAwCICQCvigEAs6IDAL7SA7SiA+4RALOiAwCFCbSiA66KAQCzogMAjZ0FAMSxAwC0ogMA5T8A04EBALOiAwCQtQO0ogPtfQCzogMA5j+0ogPUgQEAs6IDAPGmBQC77QIAtKIDAOU/ANOBAQCzogMAkLUDtKID730As6IDAOY/tKID1IEBALOiAwCFFqi/Atr3BdxoAIAErTSSmgH/Aa6iApGaAZAL3GgAgAStNJKaAf8B298ChSzrtwauNJSaAYICrjSTmgGAAoaBAgDsCa40lJoBgAKuNJOaAYACqYIFi27QxgWQYgCfHIcxkpoBkA6MkAKRmgGrTpBiAKEchzGSmgGSDu/vBYUsp4gFiDGUmgGPDogxk5oBkQ7w8AEAq0WIMZSaAY8OiDGTmgGPDtsol9EBBOQ2hSz2RcWkA4YssiOOE4UsmlDewQQA1vIBuZEDAMxz2tUDvOQD5Ay5BLvkA6YB85UDvOQD7nS6BLvkA6MByt0DrvYCvjG5BKfKAqQB/Tm++gPYENGLAgCITbk+lbAB/hG8BKfKAqMB9TbGxwSvowHwNZKPAZZGjrECAOtX/xORjwH3T8XlAYdNsvEBmo8CAItO5RrZ1gXZ4AWg2wEAAM9t8q0D7Rw=",
      "index": "AAICAwQCAwYCBwgFCAICAwQCAwYCBwgFCQEUERICDwgKERICDQYKDxACBwEMCQoCDQYKDxADBwYIDQ4CCQEOCwwDAwEMCQoCDQQMDxADBwQKDQ4BBwEOCwwBCwQMDxABNxQFDQ4LMAEIBQYCCQQCBQYCLwQGCQoHBQYUGRoFBQESDxAFAgEQDQ4DJQwBCQoDNAICAwQCAgEEAQICBwoCCwwCBwgCCQoCAgIXFhUBHAICAwQCAAEEAQICAAEEAQICAAEJDAsBEAICAwQCAAEEAQICAAEEAQICAAEJDAsBEAICAwQCAAEEAQICAAEEAQICAAEJDAsBEAICAwQCAAEEAQICAAEEAQICAAEJDAsBEAICAgICAgICAgICAgICAgICAgICAgICAnMPhAGDAYYBdRcGEhECBRgLCwwJFnYCd3iDAYABhQEEggGBAYgBjQEBDgsMBwSEAQSHAYgBhQGEAYcBjAEDBAKNAQEMCQqCAYUBAYwBiQGKAYcBA4YBCI0BjgEBAQEIBQYCCYEBjgELDAOJAQGSAY8BkAEBjwGIAQyTAZQBAQkCDA0OARsEdXJxAYoBAQgFBgIJBAIFBgIEAgIDBAIDBgIHCAUIAgI=",
      "ao": "HB8fHB8ZHx8fHx8fHBcWHBYcFxUTFxMUGB8fGB8bHx8fHx8fExMZExkcGx8fGx8RHx8fHx8fHBoWHBYSHBkRHBEYER8fER8cHx8fHx8fHxEfHx8fExMfEx8fGBEcGBwfHRweHR4fHB8fHB8cHx8fHx8fHx8fHx8fHx8fHx8fHBQaHBocHx8RHxEeHx4fHx8fHx8fHx8fHh8aHhodHx8fHx8fHh8eHh4THx8fHx8fFhwYFhgWFhcZFhkYGB8fGB8YGBsaGBoYGB8SGBIUFhUaFhoYGB8fGB8YGBkZGBkYGB8fGB8YGBkZGBkYGB8eGB4XExccExwXGB8fGB8YFxoaFxoYGB4UGBQWFBEZFBkYHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHB8fHB8ZHx8fHx8fHx8fHx8fHxwZHxkfGR4eGR4XHx8fHx8fHxkbHxsfFx4eFx4ZHRobHRsdHx8fHx8fHxsZHxkfGR4dGR0ZHBkWHBYaEx4eEx4SHx8fHx8fHxkbHxsfHB0fHB8fExkdEx0aGRYdGR0dHR8cHRwTHx0SHxIfGRof",
      "aoLevels": 32,
      "material": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAwMDAwMDAwMEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQF"
    },
    {
      "name": "Fire",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.6496288180351257,
        0.019999999552965164,
        -0.6496288180351257
      ],
      "scale": [
        0.000019825400718245997,
        0.00002899214095569834,
        0.000019825400718245997
      ],
      "triangles": 88,
      "vertices": 72,
      "positions": "hPoFAILaB/qFAgDRuwL7JQC1mAPRuwIA+YUCtZgDAPwl+YUCANK7AvwlALaYA9K7AgD6hQLvnAGyBbPyBtdWxNMCnXbyowYAANdWw9MCnnblpQXE0wLnTorVBQAAsf4Ej4wBnHbapwQAAIx+kIwB1LMG11bD0wKddqQvxNMC6E7XVo+MAZt25aUFkIwB0p0B2FbD0wKddqMvxNMC6E7YVo+MAZt2uWbkCunkBcQf+Bq8sQPk2gKmO9EXwx+lO72xA92bAvcazPoG5NoC+BrRF6C7AgCPyQPBH/cau7EDhj8A+OIGzfQFwDDnmQMAyzjjL8leAAAAzDjkL8peyzjiL8leAACY0wbtEuEvAMw44y/KXgAAAMs45C/JXsw44i/KXgAAo5ICvA3pbrfAAu6LApbtAex57YsCxyaWhwLuiwKzSvHXAbjxA82jAYuaArfxA7dsmiTtiwLskwHo3ALuiwLnhAKZlgHtiwKaPoM0AI7yA4uUApyiAcBw3poBm6IB7gjuWJyiAZgT9ZcBoq0C5XzRP6GtAuuSAaoFm6IBjIMBpO4BnKIBh2fzdJuiAacS8q8DAKg657UB0LwBpswBtDHPvAHxR8itAdC8AfNL+9QBqN4CyAblnQGn3gLbUeZAz7wB1BKUngHQvAG5pgHfGc+8AYYi",
      "index": "AAICAAICAAICAAINAAQEAAQLEAICAwQCAwYCBwgFBAQCBQYDAwEMCQoCDQYKDxADBQQICwwBAQEIBQYCCQQICwwDAwIICQoBAQEVGBcBGAQTEA8FGgIREA8DGAICAwQCAwYCBwgFAgEIBQYCCQYGCwwDBgICAwQCAwYCBwgFBAcGAgEEAwEGAgICAwQCAwYCBwgFBAcGAgEEAwEGAgICAwYDBAIFAgYCBwEIBwYCAgICAwEEAwEGAgkFEAEHCAUBDAICAwYDBAIFAgYCBwEIBwYCAgICAwEEAwEGAgkFEAEHCAUBDAICAwYDBAIFAgYCBwEIBwYCAgICAwEEAwEGAgkFEAEHCAUB",
      "ao": "Gh0cHBsaGh0cHBsaGhwaGhwaFx8fFx8XHx8fHx8fHBUUHBQcFx8fFx8XHx8eHx4fGxUVGxUZFx8fFx8XHx4eHx4eGRUVGRUZGB8fGB8YHh4fHh8fGBYVGBUcGREWGRYRERgREREWERYREREYFhIYFhgREhgbEhsbGRgbGRsbGBMbGBsbHx8fGBgbGBsaFxccFxwbGBgaGBocHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "BgYGBgYGBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBwcHBwcHBwcICAgICAgICAgICAgICAkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQoKCgoKCgoKCgoKCg=="
    },
    {
      "name": "HoardBand",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5,
        1.25,
        -0.05000000074505806
      ],
      "scale": [
        0.000015259021896696422,
        0.0000021362646662725995,
        0.0000015259022124073566
      ],
      "triangles": 6,
      "vertices": 8,
      "positions": "AAAAAP7/BwD+/wcAAAD9/wcAAAD+/wcA/v8HAP3/BwAAAP3/BwA=",
      "index": "AAICAwQCAgICAwQCCQEKBwgB",
      "ao": "Hx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "CwsLCwsL"
    },
    {
      "name": "HoardBeacon",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.10999999940395355,
        0,
        -0.10999999940395355
      ],
      "scale": [
        0.0000033569847990830412,
        0.0000033569847990830412,
        0.0000033569847990830412
      ],
      "triangles": 12,
      "vertices": 8,
      "positions": "AAD+/wcA/v8HAAAA/f8HAP3/BwD+/wf+/wcAAP3/BwAA/v8H/v8HAP3/BwA=",
      "index": "AAICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUK",
      "ao": "Hx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "DAwMDAwMDAwMDAwM"
    },
    {
      "name": "HoardFlag",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.029999999329447746,
        0,
        -0.029999999329447746
      ],
      "scale": [
        0.000011902037069191238,
        0.00003509574963479491,
        9.155412933378423e-7
      ],
      "triangles": 14,
      "vertices": 16,
      "positions": "4k4AgIAErycA//8DAP7/B6pV6CAA1qoDmUj9/wcByAb+/wcA6iD9/weAgAQA/v8HqVWwJ9nVAbHmApyxBwAAAPLDAQCbsQcAAJyxB/HDAcOIAZuxBwABAPLDAQCcsQcAAg==",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIBwEGAwQEAgICAwQCAgICAwQC",
      "ao": "GBgeGB4fGBgfGB8fGBgfGB8fGBgfGB8eHx8fHx8fHh8fHh8eHx0eHx4f",
      "aoLevels": 32,
      "material": "DQ0NDQ0NDQ0NDQ4ODg4="
    },
    {
      "name": "HoardGate",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5,
        0.059999942779541016,
        -0.004000043962150812
      ],
      "scale": [
        0.000015259021896696422,
        0.00001815823693019698,
        1.2207284889205184e-7
      ],
      "triangles": 4,
      "vertices": 8,
      "positions": "AAD+/wf+/wcAAAD+/wcA/f8HAAD+/wf9/wf7/wf9/wcAAQD+/wcA/v8HAAI=",
      "index": "AAICAwQCAgICAwQC",
      "ao": "GRofGR8fGRkfGR8f",
      "aoLevels": 32,
      "material": "Dw8PDw=="
    },
    {
      "name": "HoardGround",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5,
        0.014999978244304657,
        -0.5
      ],
      "scale": [
        0.000015259021896696422,
        6.537092917114826e-13,
        0.000015259021896696422
      ],
      "triangles": 2,
      "vertices": 4,
      "positions": "AP7/B/7/B/7/BwAAAP3/B/3/B/3/BwAA",
      "index": "AAICAwQC",
      "ao": "Hx8fHx8f",
      "aoLevels": 32,
      "material": "EBA="
    },
    {
      "name": "HoardNotice",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.3199999928474426,
        0.6699999570846558,
        -0.0030000279657542706
      ],
      "scale": [
        0.000009765773795603651,
        0.000007019150654565845,
        9.155455850814531e-8
      ],
      "triangles": 4,
      "vertices": 8,
      "positions": "AAD+/wf+/wcAAAD+/wcA/f8HAAD+/wf9/wf7/wf9/wcAAQD+/wcA/v8HAAI=",
      "index": "AAICAwQCAgICAwQC",
      "ao": "Hx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "EREREQ=="
    },
    {
      "name": "HoardPost",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.04242640733718872,
        0,
        -0.04242640733718872
      ],
      "scale": [
        0.0000012947709571126489,
        0.000021667810438462743,
        0.0000012947709571126489
      ],
      "triangles": 10,
      "vertices": 8,
      "positions": "/v8HAAD9/wcAAAD+/wcA/v8HAAD9/wf9/wf+/wcA/v8HAP7/B/3/BwAA/v8HAA==",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIBwEGAwQE",
      "ao": "GBgfGB8fGBgfGB8fGBgfGB8fGBgfGB8fHx8fHx8f",
      "aoLevels": 32,
      "material": "EhISEhISEhISEg=="
    },
    {
      "name": "HoardSheet",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5,
        0.029999971389770508,
        -0.004000043962150812
      ],
      "scale": [
        0.000015259021896696422,
        0.000018616007150533752,
        1.2207284889205184e-7
      ],
      "triangles": 4,
      "vertices": 8,
      "positions": "AAD+/wf+/wcAAAD+/wcA/f8HAAD+/wf9/wf7/wf9/wcAAQD+/wcA/v8HAAI=",
      "index": "AAICAwQCAgICAwQC",
      "ao": "GRkfGR8fGRkfGR8f",
      "aoLevels": 32,
      "material": "ExMTEw=="
    },
    {
      "name": "HoardSheetAlt",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5,
        0.029999971389770508,
        -0.004000043962150812
      ],
      "scale": [
        0.000015259021896696422,
        0.000018616007150533752,
        1.2207284889205184e-7
      ],
      "triangles": 4,
      "vertices": 8,
      "positions": "AAD+/wf+/wcAAAD+/wcA/f8HAAD+/wf9/wf7/wf9/wcAAQD+/wcA/v8HAAI=",
      "index": "AAICAwQCAgICAwQC",
      "ao": "GRkfGR8fGRkfGR8f",
      "aoLevels": 32,
      "material": "FBQUFA=="
    },
    {
      "name": "HoardStop",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.019999999552965164,
        0,
        -0.27000001072883606
      ],
      "scale": [
        6.103608622252282e-7,
        0.000008239872151639156,
        0.000008239872151639156
      ],
      "triangles": 12,
      "vertices": 8,
      "positions": "AAD+/wcA/v8HAAAA/f8HAP3/BwD+/wf+/wcAAP3/BwAA/v8H/v8HAP3/BwA=",
      "index": "AAICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUK",
      "ao": "GB8fGB8YGB8fGB8YGB8fGB8YGB8fGB8YERERERERHx8fHx8f",
      "aoLevels": 32,
      "material": "FRUVFRUVFRUVFRUV"
    },
    {
      "name": "HoardWorker",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.16167961061000824,
        0,
        -0.12990380823612213
      ],
      "scale": [
        0.000004934145437094934,
        0.00001632715422983272,
        0.000003964410108678481
      ],
      "triangles": 35,
      "vertices": 33,
      "positions": "2owGANKwArWZBAAAsRb4kQOjEZrGBAAA568E95ED/q8DsRb4kQOkEeivBPeRA6MRshb4kQOkEY2jApET07UF/f8DAIzEArx4wtgCjCLChwMA6fcBtbwCwdgCjuIFukrC2AKjWbSuBMHYAqRZuUrC2AKjWYKOAsHYAouzA7t4wtgCjCLNpwGRE+2nAem/AwAAmQuO3AH3DZ7WAwAAg8sDjdwBqrsEmQuO3AH4DYTLA43cAfcNmguO3AH4DfLvAdkcz6QCgdsDtHwAwu0Bs3z+/wOB2wMAAL/tAQD9/wPA7QEA//8DgtsDAAA=",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAg8GCgkMAAsBAAYECQoEAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAAEEAAMGAAUIAAcKAAkB",
      "ao": "GBgTGBMTGBgUGBQUGBgVGBUUGBgUGBQUHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fGhgaGhoaGhoaHh4bHhsbHBEcHBwcEREbERsbER0dER0cHx8fHx8fHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "FhYWFhYWFhYXFxcXFxcXFxcXFxcXGBgYGBgYGBgZGRkZGRk="
    },
    {
      "name": "Pothole",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.6927312016487122,
        0,
        -0.7410672903060913
      ],
      "scale": [
        0.000021057100893385743,
        0.000007934691095239394,
        0.00002412554000274735
      ],
      "triangles": 96,
      "vertices": 72,
      "positions": "xvAHsiec+AT9nwGmbKccp3sA9toB0lelbLJzzeoCpmyDd/EgpWzQjQGn2AGmbIHrAeuEAaVs7kzckAGmbJm3AuOjAaVs/RzqigKmbL2yAZFZpWyrdbzsAqZsnC2uH6VsgYcBuqQBpmzstQKuiQGlbLtPyXfYE/ygAptrALC+AY3vAQCVA9nYAQCbUaoKAOHLAc5ZALO0AbbvAQDbPqKqAQCEmAGk1wGJO7nxAfmbAdiTAo0qiyPXkwL+Yvl/AIGPAfTOAQDbT8hyAKSiA48v9sQB51CLb/XEAa4x2EQAiXqgkAEAvhuf+gUAos0EjS26/AIAzUkAoEAAufwCsCfNSbr8As9njy25/AIA3na6/AKfQAC5/AKvJ540zrEE0GedNJzYAgAAm9gCzC2fNADLLaA0AMst4NwGzbEEulSNLbr8AgDNSQCgQAC5/AKwJ81JuvwCz2ePLbn8AgDedrr8Ap9AALn8Aq8nnjTOsQTQZ500nNgCAACb2ALMLZ80AMstoDQAyy2Z4QTNsQSVwATVkwH+/wf3DMYf/f8Hyn7bnwEAoz22EQDBlwG8qgEArSDKgwYAyvgDjWi64gaVPscjueIG0mnDWgDBZt5TAOlqpI4BAMAk",
      "index": "AAICAwQCAAEEAQICAAEEAQICAAEEAQICAAEEAQICAAEEAQICAAEEAQICAAEZHBsBAh4CHyAdAB4CHyAbABwCHR4ZABoCGxwXABgCGRoVABYCFxgTABQCFRYRABINAwQdIAEOAAEBAAEBAAEBAAwDAAMDDgICAAEEAAMGAAUBCgICAAEEAAMGAAUBCgICAwQCAAEEAQICAAEEAQICAAEJDAsBEAICAAEEAAMGAAUBCgICAwQCAAEEAQICAAEEAQICAAEJDAsBEAICAAEEAAMGAAUBJw4EERIPABACERINAA4CDxALAAwHAwQNGg4EERIPABACERINAA4CDxALAAwHAwQNGAICAAEEAAMGAAUIAAcBDAICAAEEAAMGAAUIAAcB",
      "ao": "HhEdHh0RER0fER8eHh4eHh4bHR4eHR4eHh4dHh0dHh4fHh8fHh8fHh8RER8REREeEREcERwdHRsdHR0eHh0cHhweHRwdHR0eHh0dHh0eHR0dHR0eHh0dHh0dHR0RHRERHBEdHR0dHR0cHB0cHB0dHRwcHB4SEh4YHR4dHR4dGh4SER0YGh4cHR4dFh0dFh0aGh0dGh0ZGh0dGh0SEh0dEh0SHh8eHx8fHx8eHh8eGh0dGh0aGh0dGh0UEhwcEhwRFhwdFh0aHx8eHh8fHh8dHh8eHR4eHR4dHR4fHR8dHR4eHR4dHR4eHR4dHR4eHR4dHR4fHR8dHB4dHB0cHB4eHB4dEh8SEh8aGh8aGh8aGR8SFB8SEh8SEh8SEh8TFR8V",
      "aoLevels": 32,
      "material": "GhoaGhoaGhoaGhoaGhoaGhsbGxsbGxsbGxsbGxsbGxsbGxsbGxscHBwcHBwcHB0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR4eHh4eHh4eHh4eHh4eHh4fHx8fHx8fHx8f"
    },
    {
      "name": "Roadblock",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.9300000071525574,
        -0.00787146482616663,
        -0.31373485922813416
      ],
      "scale": [
        0.000028381780946137403,
        0.00001934647829845767,
        0.000010585715334703023
      ],
      "triangles": 106,
      "vertices": 88,
      "positions": "AJaDBLD7A9aqAQAAiEKm8gEA1aoBAACikwKl8gEA1KoBAACKQqbyAQDVqgEAAKKTAqXyAQDWqgEAAIhCpvIBANWqAQAA2+wFpfIBx1gApvIBAMxoAACKQqXyAQDUqgEAAIdCpvIBANSqAQAAiEKl8gEA1qoBAACHQqbyAQDUqgEAAIpCpfIBANSqAQDIWACm8gEAh0IAx1iIQqXyAQD9/wem8gHIWP7/BwDHWLOtB43vBYHxAoMhrgblMeAC1OYGtIAD5BjhBKwlwxvN7gaTwgLgAuzpBsLnAqQeveMGoqEDgyGtBuUx4ALs6Qa/5wLkGOIErCXDG/HhBuClA+AC1OYGs4ADlKUHge0G++sDgyGuBuUx4ALU5ga0gAPiGOEErCXBG83uBpPCAuAC7OkGwucCpB694waioQODIa0G5THgAuzpBr/nAuIY4gSsJcEb8eEG4KUD4ALU5gazgAOlKeEEtCcAsJEBAAAAlewBAK+RAQCMY7CRAQAAr5EBAACwkQGW7AEAr5EBAI35BJ/oBtLOAbshzqkBAM02ALaSAQDNqQHgWc02zqkBlewBuyHNqQEAiljOqQG1kgEAzakB3VngJq76AZTsAd8mupkBAAC5mQH2Z+EmAPVn4iYA82fAkASt+gH0Z7shzqkBAM02ALaSAQDNqQHgWc02zqkBlewBuyHNqQEAiljOqQG1kgEAzakB3VniJq76AZTsAeEmupkBAAC5mQH2Z98mAPVn4CYA82c=",
      "index": "AAICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCKwYGCwwJBgYGCwwJBh4CHyAdCgEGAwQBBgEGAwQBBgEIBQYCGx4FFxgIIRc4HyAdHAQHBAMBDAICAwQCAwYCBwgFBAcGAgEEAgICAwQCAwYCBwgFBAcGAgEEAgICAwQCAwYCBwgFBAcGAgEEAgICAwQCAwYCBwgFBAcGAgEEAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAAEEAQICAAEEAQICAAEJDAsBEAICAAEEAAMGAAUBCgICAwQCAAEEAQICAAEEAQICAAEJDAsBEAICAAEEAAMGAAUBJw4EERIPABACERINAA4CDxALAAwHAwQNGg4EERIPABACERINAA4CDxALAAwHAwQN",
      "ao": "HR8fHR8VHx8fHx8fHx4eHx4fHh4eHh4eHx8fHx8fHx8fHx8eHx8fHx8fHx8fHx8fHh0eHh4eHh4fHh8fHx8fHx8fHh8UHhQdHR4cHRwcHx8fHx8fHx8fHx8fGRkfGR8fGBgeGB4fGRccGRwaFhoaFhocGBkfGB8fGRkfGR8fGRkRGREXGBgYGBgRGhcYGhgWFhkWFhYXGBcRGBEYGRkXGRcRHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fGR0dGR0aGR4cGRwZGR0eGR4ZGR0dGR0aHx8fHx8eHh0eHx0fGRwdGR0ZGR0eGR4aGR0dGR0aGh0dGh0ZHh8eHx8fHx0eHh0eHR4eHR4dHh8eHh4cHR4eHR4eHR8eHR4dHB4eHB4dHR8eHR4eHR8fHR8dHR4eHR4d",
      "aoLevels": 32,
      "material": "ICAgICAgICAgICAgISEhISEhISEhISEhISEhISEhIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIyMjIyMjIyMjIyMjHR0dHR0dHR0dHR0dHR0dHR0dHR0dHR0dHh4eHh4eHh4eHh4eHh4eHg=="
    },
    {
      "name": "Scaffold",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -2.1818199157714844,
        0,
        -0.38181978464126587
      ],
      "scale": [
        0.00006658487573881084,
        0.00012359808318409591,
        0.000012971756523221384
      ],
      "triangles": 181,
      "vertices": 177,
      "positions": "+A4ArvsG9w4AAAD29AYA+A4AAPcO9fQG1EwA9vQGAPgO9fQGAAD29AYAhvEH9fQG00z3DgAAAPb0BgD4DgAA9w719AbUTAD29AYA+A719AYAAPb0BgCF8Qf19AaByAf3DgAAAPb0BgD4DgAA9w719AbUTAD29AYA+A719AYAAPb0BgCG8Qf19AbTTPcOAAAA9vQGAPgOAAD3DvX0BtRMAPb0BgD4DvX0BgAA9vQGAMH4B5PIA/yyBgCUBwCG8QcAAACTBwCF8QeUB5BEhvEHAACF8QeTBwCG8QcAAIXxB/CsAo9EAJQHAIbxBwAAAJMHAIXxB5QHkESG8QcAAIXxB5MHAIbxBwAAhfEH36gDj0QAkgcAhvEHAAAAkQcAhfEHkgeQRIbxBwAAhfEHkQcAhvEHAACF8QebiAKPRACUBwCG8QcAAACTBwCF8QeUB5BEhvEHAACF8QeTBwCG8QcAAJHuBy7zB+cFuAYAhvEHmogCAOgFtQYA7fYH44ECkkSG8QeaiAIAnesH0Y4CAIbxB5yIAgD58weiCL2OAQCOCgAAAJXLBgCNCgCG8QeOCgAAjQoAAI4KlssGAI0KAIXxB/CsAgAAjgoAAACVywYAjQoAhvEHjgoAAI0KAACOCpbLBgCNCgCF8QfhogKEBobxBwAAAOIWAIXxBwAAAI6WAgCG8QcAAADiFgCF8QcAAN4Low2mTq7cAwAAAKTiAQCt3AMAAK7cA6PiAYMGrdwDAAAApOIBAK7cAwAA7iCj4gGEBq7cAwAAAKTiAQCt3AMAAK7cA6PiAYMGrdwDAAAApOIBAK7cAwAApagC0ZgEn7ME5ycAANUBjDWjBZIrAAC7KYs1goQB1QGMNaQFvimLNaMF1AGMNaQFxxXBAv3TAfclAIZj9gjALbYKgh0A30u5F78tyuEBwgXALaMbsim/LaQbwwXALaMbghS/LfuEAfUIwC22CrUMwwKlM5chAABpih2hBOwiAACBIokdzq4BaYodoASCIokdnwRqih2gBOQR4wO1WZkjthAAzBG1ELycAZkjAADLEQC7nAHMEQC9nAGaIwAAsIAC3LsDpv4EAOgbAAAA/4gCAOcbANAz6BsAAOcbAADoG4CJAgDnGwCXuwaT7gWYMACwTgAAAJcwAK9OAL6RAbBOAACvTgAAsE6YMACvTgD7vQLYrQWdPIMHAJEkAKLKAYQG7gUAjh7zDKHKAQCWAaLKAQDwBaHKAZIkAKLKAYMGhAfXPKUZ/KgBAAAA0DcA+6gBAAD8qAHPN88J+6gBAAAA0DcA/KgBAAA=",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAg8GCgkMAAsBAAYECQoEAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAAEEAAMGAAUIAAcKAAkBDgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIBwEGAwQEAgICAwQCAgICAwQC",
      "ao": "GBgfGB8fGBgfGB8fGBgfGB8fGBgfGB8fGBgZGBkcGBgcGBwZGBgfGB8fGBgfGB8fGBgfGB8fGBgfGB8fGBgfGB8fGBgfGB8fGBgfGB8fGBgfGB8fGBgfGB8fGBgfGB8fERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERER0aERoRHx4fHx8fGRERGREdGhoRGhEREREREREREREaERoaEhESEhIREREZERkZEREYERgZGhoRGhEREREREREREREZERkaERISERIREREZERkZEREZERkYERERERERERERERERHx8fHx8fExIaExofHx8fHx8fEhMfEh8ZGBgTGBMTGBcUGBQUFhYUFhQUGBkUGBQUHx8fHx8fHx8fHx8fHh8eHh4eHx8fHx8eHx8eHx4fGhgaGhoZGhkaHx8bHxsaHREcHRwcEREaERoZERwcERwcHx8fHh8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fGx8fGx8YHB8fHB8fHhsUHhQeHx8fHx8fEREeER4fEREfER8fEREfER8fEREfER8fHx8fHx8fHR8fHR8eHx4eHx4f",
      "aoLevels": 32,
      "material": "JCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSYmJiYmJiYmFhYWFhYWFhYXFxcXFxcXFxcXFxcXGBgYGBgYGBgZGRkZGRkMDAwMDAwMDAwMDAwVFRUVFRUVFRUVFRUNDQ0NDQ0NDQ0NDg4ODg=="
    },
    {
      "name": "Signpost",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.10000000149011612,
        0,
        -0.38999998569488525
      ],
      "scale": [
        0.0000030518044248147132,
        0.00003631647386039396,
        0.00001190203664285909
      ],
      "triangles": 82,
      "vertices": 67,
      "positions": "/v8HAICABP//AQDZccsZ7ESwC7LmAQCqZuPMBetE2XHMGexEsAvLmQLrRKpmmjPsRADmzAHrRNhxzBnsRK8LsuYD60SwC8sZ7ESvC+ZMAKdmy5kBAJtE5QzChwfYBeaMAQDEPpmzA8GHB5tE5gzChwfYBbGmAcGHB8Q+zBnChwcAgIABwYcHmkTmDMKHB9cFtKYCwYcH2AXlDMKHB9cF5IwCAME+yZkD0DMA5MwBzzP6WsmZAwAA5cwBAPla5swBAPtaypkDAAAAgyud7QEAhVYAAACykAUAhCvmtwEAgivltwGaswKFVgAAALGQBQCGVgAAALKQBQCBK+a3Af3/B42sAZfIBgAAspAFAIZWAAAAsZAFAIEr5bcBmLMCgiuYyAYAhVYAAACxkAUAhCvltwEAgivmtwECj8kE5LcFALTpAgAAAJXfBQCz6QIAypkDtOkCAACz6QIAALTpApbfBQCz6QIAkAW2IuFOAADRwQQAyKQCAAAA0sEE6aMDx6QC0cEEAADSwQQAyKQCAAAA0cEE",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAgQCBQYDAhMGDg0QAA8BAAYEAAQEEQoIAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAgQCBQYDAhMGDg0QAgICAAEEAAMGAAUIAAcKAAkBDgICAAICAwQHCgICAAICAwQHCQgIDxABBwEGAwQIDwEOCwwBAwEMCQoBCwEKBwgBCgICAAICAwQHCgICAAICAwQHCQgIDxABCQEKBwgBAQEMCQoBDQEOCwwBBQEGAwQIAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAgICAwQC",
      "ao": "GBgcGBwcGBgbGBscGBkcGBwcGRkcGRwcGBgbGBscGBkcGBwcHBwcHBwbGxscHBscGBgWGBYXGBgXGBcXGBgYGBgYGBgYGBgZGBgXGBcXGBgXGBcXHx8fHx8fHx8fHx8fHx8fHx8fHh0dHR4eHR4eHx8fHx8fHx8fHh8fHh8eHx4eHx4fHx8fHx8fHx8fHx8fHRscHRwdHx8fHx8fHx8fHR4eHh8dHh0dHx8fHx8fHx8fHx8fHx4eHx4fHh4eHh4dHRwbHRsdHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx4eHx4fHh4dHh0eHx8fHx8fHx8fHx8f",
      "aoLevels": 32,
      "material": "JycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJygoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKSkpKQ=="
    },
    {
      "name": "Survey",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.5158477425575256,
        0,
        -0.5346410274505615
      ],
      "scale": [
        0.000016568974371022632,
        0.00001724269467050627,
        0.000016083800657177312
      ],
      "triangles": 125,
      "vertices": 115,
      "positions": "7oAEzA20nwezGqkJpRkA0p8GqdoCgiHUC84ftTv7oQaC1ALLBvyhBoHUAoAh0ZgGqO0CAKikBtfNAoTwAselBueuAucZswPFG4WeApCjBqqjAaIgpAS4IsjlAZO0Bu2rAYukAvqfBuapAfS9AsWcBp+OAdGdAuigBtiwAZP4ApukBp3MAZsY4AzzGYaeApCjBqqjAaIe9Q+wII/WAuWPBpOoAcqXAoCkBpyqAa3/Ad+wBqeQAdKdAuigBtiwAaqrAaUMTMk4APlkAKgtAMo4APpk36kBpy35ZACoLQDJOKct+mQAqC0AyjinLfpkAKgtAJZxpy0AAKgtAPGWAQCsGQCetQEAAADL/AEAnbUBAM68AZ61AQAAnbUBAACetQHM/AEAnbUBAKVA2psBkx2BPAAAqgOZA7ibAaw1AADVOLs2t5sBqgOaA7ibAdg4mQO3mwGrA5oDuJsB2q4D/a8HgaAEwTEAuR0A1vQBAMIxALodwTHV9AG4HQDW9AEAwjHW9AG3HcExALkdANT0AQDCMQC6HcEx0/QBuB0A1PQBAADW9AHxOsIxALodwTEAuB2HkQbV0ge6sQXJOADTIa4C7KADmgTAMQC6He0z66AD0iGuAuygA5kE0qgG66ADgQrJOADTIa4C7KADnATAMQC4He0z66AD1CGuAuygA5kEoZ0C66ADh8IHyzgA0yGuAuygA5oEwjEAuh3vM+ugA9QhrgLsoAObBJHyArc/2PUG4KkBAAAAsDYA36kBAADgqQGvNvED36kBAAAAsDYA4KkBAADWyASvNqoX4KkBAAAAsDYA36kBAADgqQGvNvED36kBAAAAsDYA4KkBAACd/QOvNt2gB+CpAQAAALA2AN+pAQAA4KkBrzbxA9+pAQAAALA2AOCpAQAAx44D45cD+oEH+4oBzPwCwzz3DMv8Au6aAYOGAQDXd4pFAKWoAdywAQDWDw==",
      "index": "AAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAgQCBQYDAhMGDg0QAA8BAAYEAAQEEQoIAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIBwEGAwQEAgICAwQCAwYCBwgFBAcGAgEEAgICAwQCAwYCBwgFBAcGAgEEDwEKBwgBBwYKDxAFAwMGAQIIAQEIBQYCCQYGCwwDAQMIAwQCAQEEAgICAwQCAwYCBwgFBAcGAgEEAwEGAgICAwQCAwYCBwgFBAcGAgEEAwEGAgICAwQCAwYCBwgFBAcGAgEEAwEGAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAwQCAgICAAEEAAMGAAUIAAcB",
      "ao": "FhYYFhgWFRUWFRYYGRkRGRETGRkTGRMRGRkRGRERGBgWGBYUFhYYFhgXGRkSGRIVGBgUGBQWGhsRGhERGRkVGRUSFhYYFhgXHh4YHhgeHh4YHhgYHh4fHh8YHx4YHxgeHh4YHhgYHh8fHh8YERkREREZGRERERkRHx8fHx8fHx8fHx8fHh8fHh8fHx4eHx4fHBwdHB0cHx8fHx8fEREfER8fEREeER4eEREdER0dEREfER8eHx8fHx8fGBgdGB0dFxccFxwdGBgdGB0dHx8fHx8fHh0eHh4fHx8fHx8fHR0fHR8fHRwdHR0eHR0fHR8fHx8fHx8fHx4fHx8fHx8fHx8fHx8fEREeER4eERgfER8fFxEfFx8fHx8fGBgfGB8fGBgfGB8fGBgeGB4fHx8fGBgfGB8fGRgfGR8fGBgeGB4eHx8fER8fER8RHRERHREeER8fER8RHxERHxEfER0eER4RHxERHxEfGhsaGRsaGh4aGR8aGh4Z",
      "aoLevels": 32,
      "material": "KioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKisrKysrKysrKysrKywsLCwsLCwsLCwtLS0tLS0tLS0tLS0hISEhISEhISEhISEhLi4uLi4uLi4uLi4uLi4uLi4uLi4uLy8vLy8vLy8vLy8vHx8fHx8="
    },
    {
      "name": "Trench",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.7600000500679016,
        0,
        -1.5070725679397583
      ],
      "scale": [
        0.000024109256161135102,
        0.000027466238686446697,
        0.00004512203579191995
      ],
      "triangles": 203,
      "vertices": 176,
      "positions": "pkfqBv7/B8LKBgAAAACb7AfBygYAAIzZA+kGtmSBdLoUgxGQtQKBBbdm5zOLAfJ2zZQChQeyZ+zzAaJy/94Bpnn6Bf4kqdEBwwLuoQGhugGbD4FC+R6zE+Rg3MQBnGe1bbfEArGTAe8qym6XLtw4jTqOIqxWvjWuB4W5AdVC+RyWrAfQ0gMAAAAA/8UGz9IDAAAAkQGAxgYAAP/FBgCEWwAAAIDGBuszwS3uDQDCLQAAANvhBgDBLQDsM8ItAADBLQAAwi3c4QYAwS0A0NIDwS3t0wYAAIDGBgCEWwAAAP/FBgDBLe7TBgDCLQAAANvhBgDBLQDsM8ItAADBLQAAwi3c4QYAwS0Au4YE6wL/3QQAnA7TCNDSAwAAAJsO1AjP0gO4HADQ0gMAAM/SA5sO1AjQ0gMAAM/SA5sO0NECAJwO0wjQ0gMAAACbDtQIz9IDuBwA0NIDAADP0gObDtQI0NIDAADt1QWe6QGwjAIAtGYAAADLyQcAs2YA7DO0ZgAAs2YAALRmzMkHALNmAKADv60C+6YH3ysAvw0AmrMCAOArAMAN3yuZswLADQCaswIA4CuZswLs9gbfKwC/DQCaswIA4CsAwA3fK5mzAr4NAJqzAgCA0QeZswLpkQffKwC/DQCaswIA4CsAwA3fK5mzAsANAJqzAgDgK5mzAuz2Bt8rAL8NAJqzAgDgKwDADd8rmbMCvg0AmrMCAKsL2QWSFQC0ZgAAAMvJBwCzZgDsM7RmAACzZgAAtGbMyQcAs2YAxbUDv60C5/0C/W0AAMsE9u4BwQGUdwAAx3L17gH6JcsE9u4BwgHKcvXuAcEBygT27gHCAck7rwv5PONoAL4c1BjmzAH+ApBQAOEV30DlzAHsQJ4P5swB6wekcuXMAewHnQ/mzAHrB6A35cwBmybTGObMAf4CpSKvC90O01sAAKMC7IIBnQGeYAAA+V3rggGaMqMC7IIBnAH4XeuCAZsBpgLsggGcAYwxhxHZGZth+kkAzjD5Sf4sm2EAAM0wAP0szjAA/SycYQAAmuECw4gBypgDAORxAAAAoUUA43EA0IEB5HEAAONxAADkcaJFAONxAK/PB5uOA/Fn1xYAjQwAkv0EANgWAI4Mry2R/QQAAJL9BADYFpH9BJAMAJL9BACZEO847FQAyL4CAAAA9cEBAMe+AgC0IMi+AgAAx74CAADIvgL2wQEAx74CAJ4DocQEhaAHtxMAsQoA/v8H3gGaEADUCNEj/f8HAJ4D/v8HAJoQ/f8HsgoA/v8H3QG4E4eRAqEH0tIDAAAAqPoBANHSAwAA0tIDp/oB4QLR0gMAAACo+gEA0tIDAAA=",
      "index": "AAICAwQCAgICAwQCBQYCAwEIAwEIAgUBCgUHAgYCBQYCBAkGAgICCQYEBwEKBQEIAQMGAgICAgMBBhkWDxAVGBEKCAcBBgQJBgUMGwgFGAEPBRoLDgICAwQCAgICAwQCAgICAwQCAAEEAQICAAEEAQICAAEJDAsBCAMBBgUKBAICAwQCAgICAwQCAAEEAQICAAEEAQICAAEJDAsBCAMBBgUKKRYGGxwZFhkGFBMWFAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAwYCBwgFBAcGAgEEAgICAwQCAwYCBwgFBAcGAgEEAgICAwQCAwYCBwgFBAcGAgEEAgICAwQCAwYCBwgFBAcGAgEEAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAg8GCgkMAAsBAAYECQoEAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAAEEAAMGAAUIAAcKAAkBDgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIBwEGAwQEAgICAwQCAgICAwQC",
      "ao": "HR4dHR0eERIRERERERERFhUbFBYaGBETGx0WGx4eFBscGhEcHh0fHx4fHx8fHh4fHx8fExEREhESEhIRERERFRIYFB0eHRYeHx8fERERERERFxwaFBUUFBQRERERERERGBobGBsaGRsbGRsXExgaExoXGhwcGhwaHx8fHx8fERERERERFxoVFxUSFhcYFhgWGRsaGRoZGxscGxwaHh4fHh8fEREZERkXEREZERkZExMTExMTGBgYGBgYGBgYGBgYExMTExMTEhMTEhMTFxcXFxcXGBgYGBgYFBMTFBMTHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHh0dHh0dHh4eHh4eFhgRFhEcGBcRGBERFxYcFxwRFRYRFREcGBgRGBERGBYcGBwRGBgRGBEcFhYRFhERGBgcGBwSGBgRGBEcFhURFhERGBgcGBwRHxEfHx8fHx8fHx8fHx8RHxEfHxERHxEfHh0dHh0eHx8RHxERERETERMTEREUERQUEhEUEhQUEREUERQUHx4fHx8fHh4fHh8fHx8fHx8fHh4fHh8fHx8fHx8fGhgaGhkaGhoaHh8bHhsaHREcHRwcEREbERsbERwdER0dHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fFhYRFhEeGBgdGB0RGBcRGBEdFhUdFh0RHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHR0eHR4eHx8fHx8fERceER4fFhgfFh8fGBYfGB8fFxEfFx8eHx8fHx8fHR8fHR8eHx4eHx4f",
      "aoLevels": 32,
      "material": "MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMBsbMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEhISEhISEhISEhISEyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIdHR0dHR0dHR0dHR0WFhYWFhYWFhcXFxcXFxcXFxcXFxcYGBgYGBgYGBkZGRkZGQwMDAwMDAwMDAwMDDMzMzMzMzMzFRUVFRUVFRUVFRUVDQ0NDQ0NDQ0NDQ4ODg4="
    },
    {
      "name": "Van",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.6600000262260437,
        0,
        -1.4999037981033325
      ],
      "scale": [
        0.00002021820474072962,
        0.00003356984890033899,
        0.00004547041759635033
      ],
      "triangles": 175,
      "vertices": 157,
      "positions": "sC7QiwXwVQDDrgQAAADWpgcA+JQBAACWQfUeAIpds3EA3ugBoXgAzhLFM7CfB8OuBJK8AgAA1aYHAMSuBAAAAMTqBADNEsYzAN3oAaJ4AIldtHEAlUH2HpfVBqCtAceVAYCLBgAAAPTNAbNq/4oGAACjTYGzAdtvAACalwEAoJ4BAAAAmZcByKUHn54BmpcBAACZlwEAoJ4BAAAAmpcB69AHk70E5QoA0oMBAJD8BwAAANGDAQCP/AfSgwGYYZD8BwAAj/wH0YMBAJD8BwAAj/wHANWzBQDSgwEAkPwHAAAA0YMBAI/8B9KDAZphkPwHAACP/AfRgwEAkPwHAAC91QdUxdUBALxKAOyuBwAAALtKAAC8SsatBwC7SgDrrge8SgAAu0oAANxvxa0HAOw3AOyuBwAAAOs3AADsN8atBwDrNwDrrgfsNwAA6zcA4oYCopcE34cHlxf6DQAAAPSMBZgX+Q0Ary4A84wFAAD0jAWYF/sN84wFAAD0jAXw5gP8DfOMBZcX+g0AAAD0jAWYF/kNAK8uAPOMBQAA9IwFmBf7DfOMBQAA9IwFm+sCpRDzEgDCPAAAAMUzAME8AOCGAsI8AADBPAAAwjzGMwDBPACGpgHRhAXV1wWTgwEAALsFvsMBwQGMjgEAAM+IAb3DAdYluwW+wwHAAdCIAb3DAb8BvAW+wwHAAYVHpwm7PPl8AKActB3IpwH8AsZfAMsVm03HpwGsQJYSyKcB4weiiAHHpwHkB5USyKcB4wf0QcenAfclsx3IpwH8AvMopQnPDqNtAADdAoZrmwHgcgAAgXCFa+gx3QKGa5wBgnCFa5sB3gKGa5wBxjr7DcEZ9XPCPAD6OcE80iz1cwAA+TkA0Sz6OQDRLPZzAADn9gK60QG0wAEAtGYAAADNSwCzZgCCqgG0ZgAAs2YAALRmzksAs2YA9qwD+4YFvFKFGwCDDADusAMAhhsAhAyLNu2wAwAA7rADAIYb7bADggwA7rADAKkTwy6aVADShAIAAAC3wAEA0YQCANIm0oQCAADRhAIAANKEArjAAQDRhAIAteUGpokCwN4ClRcApwoArvQC3AGoEwDMCL8qrfQCAO4DrvQCAKoTrfQCqAoArvQC2wGWF7XfAZsHuKwEAAAA5swBALesBAAAuKwE5cwB3wK3rAQAAADmzAEAuKwEAAA=",
      "index": "AAICAAICAgICCQQCBA0EAAYEAgICAAICAgICCQQCBA0EAAYEGQwOGRoXBRQBERIPDAgBBQYTChABDQ4LBRgBFRYTBRABDQ4LCAwBCQoHBRQBERIPFgICAwQCAgICAwQCAgICAwQCAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAAEEAQICAAEEAQICAAEJDAsBEAICAwQCAAEEAQICAAEEAQICAAEJDAsBEAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAwYCBwgFBAQCBQYDAgQCBQYDAg8GCgkMAAsBAAYECQoEAgICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAAEEAAMGAAUIAAcKAAkBDgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIAgICAwQCAAEEAQICAAEEAQICAAEJDAsBBgQEBwgNCAMBBgUKBAICAwQCAwYCBwgFBAQCBQYDAgsGBgUIBwEGAwQEAgICAwQCAgICAwQC",
      "ao": "HxESEh8fHx8fEh8fHx8SEh8fEhIfHx8fHx8fHx8fHxIfHx8fEhIfEh8fHx8SHxISHh8fHh8fHh8fHh8fHx8fHx8fEhISEhISHh8fHh8eHx8eHx4eHx8fHx8fHx8fHx8fHx8fHx8fFxoZFxkWGhoZGhkZGRYXGRcZERERERERFxkZFxkXGRkYGRgZGRYWGRYZERERERERGR0bGRsZGRwdGR0ZGR0dGR0aGh0dGh0ZHh8dHh0dHh8fHh8eHh8fHh8eHh8fHh8eGxwdGx0dHh4eHh4eFRQXFRcYExQXExcWHh4eHh4eHBsdHB0eExMWExYXFBUYFBgXHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fGBgTGBMTFxYTFxMTFRURFRERFhcTFhMTHx8fHx8fGRYWGRYYERERERERFhsaFhoXHx8eHx4fGBgYGBQUGBQYHh8aHhobGxEXGxcbERERERERERwbERsYGRkWGxYdGxgYHR0eHx4fHx0dHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fGBYRGBEdFBMdFB0RFRURFREdGBgdGB0RERISERIRGBocGBwaHx8fHx8fGRwZGRkYGBkZGBkYHxsbHxsfFhceFh4fGBkfGB8fGxsfGx8fGhgfGh8fHx8fHx8fHR4fHR8eHh0eHh4f",
      "aoLevels": 32,
      "material": "NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDU1NTU1NQICAgICAgICAgICAgICAgI2NjY2NjY2NgQEBAQEBAQEJCQkJCQkJCQkJCQkJCQkJCMjIyMjIyMjIyMjIxYWFhYWFhYWFxcXFxcXFxcXFxcXFxgYGBgYGBgYGRkZGRkZDAwMDAwMDAwMDAwMMzMzMzMzMzMVFRUVFRUVFRUVFRUNDQ0NDQ0NDQ0NDg4ODg=="
    },
    {
      "name": "Wreck",
      "origin": [
        0,
        0,
        0
      ],
      "lo": [
        -0.7135903239250183,
        0,
        -1.242588758468628
      ],
      "scale": [
        0.000021467777668970476,
        0.000021619544637151375,
        0.00003809356813146292
      ],
      "triangles": 126,
      "vertices": 103,
      "positions": "sLsG5q0C8CyrCM78AYQKwBPiGrpbvBXJvALPDNuDAa7kA+VGnBDYPvJc0+4Dx2nxXJk2xc8BgwiBGPIWulv6MrjzAbwJsgqphAT5bq8ZsyruWN77BJjCAqC6A7wVybwCzQyz/QSi9AOKFvaJBOIuAPWYBL/dBIkW+SOkuwLODJaeBeIXsK8BlBSdrgKFDMdDtNUC4g2/6wT3YtsByif+LtwB9QTz2wLhDZDnBKzjAcT9AYoJk7QBlQejSLToAbwJ9ewDlSwA4zTRPqUCyBftsgGVB9yjBKFM02flGOyQAvQK3QGSE72bAeYY7ZAC8wqYW6CbAvQK5hjtkALzCocX3P0BsqYB5hjrkALzCvvMBeoImc0E5RjukAL0Ct8BkBO9mwHmGOuQAvMKmFugmwL0CuYY7ZAC8wqHF9z9AbKmAeYY65AC8wrC3gP0KeQH7w7cowHGBvMBhhWFqwHwDtujAcMGjmWOrgHEBvAO26MBwwb7DNaOAcqxAfAO26MBxQaViwW0uwTMqgL/Ct3IAZyQAbaYBIowAP8uxMMBm5ABkZYDp5MClssBpByDRpKRAbiHA4ojAJoP9kmRkQGZzAOR/QOG0wGXIYJQpAM7hAXzKJghgVClA+ahBPC7AsoKmCGBUKMD3SD+SposmCGBUKMDq/wB2pME96AF31u2gAKaHO4spY8CqhHNXnQw2y/oD5Mt8i7wDsMtzl5zL+yZAfWABoLZA8jcAQDjlQH7HwDlwQHjiQIApXzx1wIAghLJ3AEA5JUB/h8A5sEB4okCAKZ88365Dqh+mXaMwAPNFOABi8AD3EXvdgCdL/4qAKdOuJEBAJMB5KsGAPGFBqVo9NoClxLGAfPaAsI98WgA1Sn2JQCLRaqAAQCDAb2wBgCU6AK3U4yhAsUOngGLoQKcMfNTAKshrB4AozfUZgBp",
      "index": "AAICAwQCAwYCBwgFCAICAwQCAwYCBwgFCQEUERICDwgKERICDQYKDxACBwEMCQoCDQYKDxADBwYIDQ4CCQEOCwwDAwEMCQoCDQQMDxADBwQKDQ4BBwEOCwwBCwQMDxABNxQFDQ4LMAEIBQYCCQQCBQYCLwQGCQoHBQYUGRoFBQESDxAFAgEQDQ4DJQwBCQoDNAICAwQCAAEEAQICAAEEAQICAAEJDAsBEAICAwQCAAEEAQICAAEEAQICAAEJDAsBEAICAwQCAAEEAQICAAEEAQICAAEJDAsBEAICAwQCAgICAwQCAgICAwQCAAEEAQICAAEEAQICAAEJDAsBCAMBBgUKBAICAAEEAAMGAAUIAAcKAAkBCgILAAQCAAICCQYEBAICAAICAAICAAINAAQEAAQLEAICAAEEAAMGAAUIAAcBCAIJAAQCBQYCBAICAAEEAAMGAAUIAAcBCAIJAAQCBQYCBAICAAEEAAMGAAUIAAcBCAIJAAQCBQYC",
      "ao": "HB8fHB8YHx8fHx8fHx8fHx8fHx4bHxsfFx8fFx8eHx8fHx8fHxocHxwfHh8fHh8RHx8fHx8fHx8fHx8fHxwbHxsfER8fER8dHx8fHx8fHx4fHx8fHx8fHx8fHxoaHxoeHx4fHx8fGh0fGh8bHR8fHR8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8eHx8fHx8fGBsdGB0ZGhoZGhkbGx8fGx8bGRoUGRQYGB4fGB8aGxoVGxUbGx0fGx8bGRoZGRkXGx8eGx4cGhcaGhoYHB8fHB8dGxocGxwaHx8fHx8fHx8fHx8fFRcVFRUUFxgXFxcYHx8fHx8fHh8aHhoYGBsdGB0dFB8UFx8WFh8bGx8cGx8cGh8TEREeHh4fHxERHh8RGx4fHx4dHR0dHR4bGx8dHR0bFh0YGh8aGR8ZGR0ZGRoYERERERERERERGh0aGhgaGhsaGh8aGh8aERERERERERERGRgZGR4aGh8aGRsYGBQYERERERERERER",
      "aoLevels": 32,
      "material": "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ3Nzc3Nzc3Nzc3AgICAgICAgICAgICAgICAgICAgICAgICODg5OTo6Ojo6Ojo6Ojo7Ozs7Ozs7Ozs7PDw8PDw8PT09PT09PT09PT09PT09PT09PT09PT09"
    }
  ],
  "markers": []
};
