/**
 * GENERATED by scripts/import-model.ts from crowd-near.glb -- do not edit.
 * The model's source is the Blender script beside it in `blender/`.
 */

import { lazyModel } from "../models/imported";

export const MODEL = lazyModel("crowdNear", () => import("./crowdNear.data"));
